# Semantic manual CSV review

이 노트북은 기존 page/chunk clean CSV와 새 semantic clean CSV를 사람이 검수하기 쉽게 비교합니다. 시각화는 pandas로 집계한 결과를 HTML bar chart로 렌더링합니다.

In [ ]:
from pathlib import Path
import pandas as pd

ROOT = Path('..').resolve()
processed = ROOT / 'data' / 'processed'
stay_current = pd.read_csv(processed / 'stay_manual_clean.csv', dtype=str).fillna('')
visa_current = pd.read_csv(processed / 'visa_manual_clean.csv', dtype=str).fillna('')
stay_semantic = pd.read_csv(processed / 'stay_manual_semantic_clean.csv', dtype=str).fillna('')
visa_semantic = pd.read_csv(processed / 'visa_manual_semantic_clean.csv', dtype=str).fillna('')

In [ ]:
overview

manual,current_rows,semantic_rows,semantic_review_rows,semantic_review_pct,nonempty_code_rows,unique_codes
stay,1065,3124,1296,41.5%,3106,95
visa,813,2076,856,41.2%,2062,78

In [ ]:
schema

column,review_meaning
manual_type,사증민원/체류민원 구분
source_pdf,원본 PDF 파일명
source_section_path,문서 구조 기반 근거 경로
visa_code,비자/체류자격 코드. 체류 매뉴얼도 검색 통합을 위해 이 컬럼을 사용
visa_name_ko,코드의 한국어 명칭
petition_type,"사증발급, 사증발급인정서, 체류자격 변경, 체류기간 연장 등 민원유형"
topic_type,"대상, 요건, 제출서류, 절차, 제한, 예외, 기간 등 지식 주제"
applicant_context,하위 약호나 신청자 맥락
answer_summary,사람이 읽는 정리문
ai_search_text,사용자 표현 매칭/임베딩용 확장 검색 텍스트
evidence_quote,검수용 짧은 근거
source_raw_text,검수용 원문 조각
needs_human_review,표/복수코드/장문/분류약함 등 검수 필요 여부

In [ ]:
# stay semantic rows by topic_type

topic_type,distribution,rows
일반,,703
요건,,544
대상,,390
제출서류,,377
수수료,,201
제한,,191
예외,,189
기간,,172
개요,,146
절차,,55
추천,,52
활동범위,,47
점수,,42
참고,,15

In [ ]:
# stay semantic rows by petition_type

petition_type,distribution,rows
외국인등록,,752
체류자격 변경,,730
사증발급,,547
COMMON,,288
근무처 변경·추가,,213
체류자격외활동,,159
체류기간 연장,,142
재입국허가,,110
사증발급인정서,,105
체류자격 부여,,69
전자사증,,9

In [ ]:
# stay semantic rows by visa_code

visa_code,distribution,rows
E-9,,382
F-4,,367
F-5,,351
D-2,,340
E-7,,254
D-10,,172
B-1,,156
F-2,,137
F-6,,136
F-1,,85
G-1,,66
C-3,,64
D-3,,49
E-2,,43
E-3,,41
H-2,,40
D-8,,36
D-4,,29
E-1,,25
C-4,,23

In [ ]:
# visa semantic rows by topic_type

topic_type,distribution,rows
일반,,521
제출서류,,306
대상,,294
요건,,292
기간,,131
제한,,119
예외,,102
개요,,69
수수료,,64
절차,,58
추천,,42
활동범위,,33
점수,,25
참고,,20

In [ ]:
# visa semantic rows by petition_type

petition_type,distribution,rows
사증발급,,"1,176"
체류자격 변경,,284
사증발급인정서,,220
외국인등록,,217
근무처 변경·추가,,77
전자사증,,45
체류기간 연장,,21
체류자격외활동,,17
재입국허가,,14
체류자격 부여,,5

In [ ]:
# visa semantic rows by visa_code

visa_code,distribution,rows
E-7,,375
F-4,,356
F-2,,102
C-3,,101
H-1,,94
F-6,,94
H-2,,72
E-9,,69
D-8,,64
D-10,,61
D-4,,55
F-5,,55
B-1,,52
E-1,,52
A-1,,45
E-3,,38
D-7,,32
E-2,,28
D-2,,27
G-1,,27

In [ ]:
query_df

manual,phrase,hits,top_codes
stay,외국인이 한국에서 법인을 만들고 살려면,39,"D-8, D-8, D-8, D-8, D-8, D-8, D-8, D-8"
stay,한국 회사가 외국 전문인력을 채용하려면,255,"E-7, E-7, E-7, E-7-Y, E-7, E-7, E-7, E-7"
stay,한국인과 결혼한 외국인은,143,"F-6, F-6, F-6, F-6, F-6, F-6, F-6, F-6-1"
visa,외국인이 한국에서 법인을 만들고 살려면,70,"D-8, D-8, D-8, D-8-1, D-8, D-8, D-8, D-8"
visa,한국 회사가 외국 전문인력을 채용하려면,382,"E-7, E-7, E-7-Y, E-7, E-7, E-7, E-7, E-7"
visa,한국인과 결혼한 외국인은,99,"F-6, F-6, F-6-1, F-6-2, F-6-3, F-6-1, F-6, F-6"

In [ ]:
# stay rows needing human review

manual_type,visa_code,visa_name_ko,petition_type,topic_type,source_section_path,review_notes,answer_summary
체류민원,,공통사항,,제출서류,유 의 사 항,대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 제출서류에 관한 정리입니다. 본 매뉴얼에서 주민등록등본 등 국내에서 발급·제출하는 서류의 유효기간은 별도의 유효기간이 설정되지 않은 경우 발급일로부터 3개월 이내임.
체류민원,,공통사항,체류자격 변경,일반,"유 의 사 항 > 체류자격 변경 > 2. 신청자가 사증발급, 체류자격 변경허가 등 신청 시 이미 제출하여 등록외국인 기록에 보관 중인 서류는 제출 생략",대표 코드 없음: 공통/부록 여부 검수 필요; 주제 자동분류 약함: 검수 필요,"공통사항 / 2. 신청자가 사증발급, 체류자격 변경허가 등 신청 시 이미 제출하여 등록외국인 기록에 보관 중인 서류는 제출 생략 / 체류자격 변경 / 일반에 관한 정리입니다. 신청자가 사증발급, 체류자격 변경허가 등 신청 시 이미 제출하여 등록외국인 기록에 보관 중인 서류는 제출 생략"
체류민원,,공통사항,체류자격 변경,제출서류,유 의 사 항 > 체류자격 변경 > 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함.,대표 코드 없음: 공통/부록 여부 검수 필요,"공통사항 / 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함. / 체류자격 변경 / 제출서류에 관한 정리입니다. 신원보증서의 보증기간이 4년 이상인 때에도 4년을 한도로 하여 이를 인정하며, 각종 허가를 할 때의 허가기간은 신원보증서의 보증기간을 초과할 수 없음.; 주민등록등본·가족관계기록사항에 관한 증명서·사업자등록증·납…"
체류민원,,공통사항,체류자격 변경,절차,유 의 사 항 > 체류자격 변경 > 8. 출입국관리법 제87조 및 동법 시행규칙 제72조 등에 따라 징수하는 각종 체류허가 등에 관한 수수료는 심사수수료로써 민원이 접수되면 반환되지 않음.,대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 8. 출입국관리법 제87조 및 동법 시행규칙 제72조 등에 따라 징수하는 각종 체류허가 등에 관한 수수료는 심사수수료로써 민원이 접수되면 반환되지 않음. / 체류자격 변경 / 절차에 관한 정리입니다. 출입국관리법 제87조 및 동법 시행규칙 제72조 등에 따라 징수하는 각종 체류허가 등에 관한 수수료는 심사수수료로써 민원이 접수되면 반환되지 않음.
체류민원,,공통사항,체류자격 변경,수수료,유 의 사 항 > 체류자격 변경 > 1. 각종 체류허가 등에 관한 심사수수료,대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 1. 각종 체류허가 등에 관한 심사수수료 / 체류자격 변경 / 수수료에 관한 정리입니다. 각종 체류허가 등에 관한 심사수수료; 여권 유효기간 범위 내 체류기간 부여 안내; 취업할 수 있는 체류자격 외국인의 직업 및 연간소득금액 신고 의무; 만 6세 이상 만 18세 이하 체류외국인의 재학증명서 제출 의무; 외국인 결핵진단서 제출 의무 관련 안내
체류민원,,공통사항,체류자격 변경,대상,유 의 사 항 > 체류자격 변경 > 1. 각종 체류허가 등에 관한 심사수수료 > 적용대상,복수 코드 포함: 코드-규칙 연결 검수 필요; 대표 코드 없음: 공통/부록 여부 검수 필요,"공통사항 / 1. 각종 체류허가 등에 관한 심사수수료 / 체류자격 변경 / 대상에 관한 정리입니다. 적용대상; 아래 외국인을 제외한 모든 장기 체류자격 외국인; 외교(A-1), 공무(A-2), 협정(A-3), 영주(F-5), 난민인정자(F-2)·그 가족(F-1), 인도적체류허가자·난민신청자·그 가족(G-1), 무국적자"
체류민원,,공통사항,근무처 변경·추가,기간,"유 의 사 항 > 근무처 변경·추가 > 1. 각종 체류허가 등에 관한 심사수수료 > 체류자격 부여, 체류기간 연장 , 체류자격 변경, 근무처 변경·추가 민원업무에 적용",대표 코드 없음: 공통/부록 여부 검수 필요,"공통사항 / 1. 각종 체류허가 등에 관한 심사수수료 / 근무처 변경·추가 / 기간에 관한 정리입니다. 체류자격 부여, 체류기간 연장 , 체류자격 변경, 근무처 변경·추가 민원업무에 적용; 체류기간 부여 기준; (원칙) 여권 유효기간 범위 내에서 체류기간 부여; 6.30.까지) 잔여 여권 유효기간이 1년 미만이라 하더라도 유효기간을 1년으로 간주하여 1년 이내에서 체류허가 기간 부여; 7.…"
체류민원,,공통사항,외국인등록,대상,유 의 사 항 > 외국인등록 > 1. 각종 체류허가 등에 관한 심사수수료 > 3 취업할 수 있는 체류자격 외국인의 직업 및 연간소득금액 신고 의무,복수 코드 포함: 코드-규칙 연결 검수 필요; 대표 코드 없음: 공통/부록 여부 검수 필요,"공통사항 / 1. 각종 체류허가 등에 관한 심사수수료 / 외국인등록 / 대상에 관한 정리입니다. # 3 취업할 수 있는 체류자격 외국인의 직업 및 연간소득금액 신고 의무; 출입국관리법 시행규칙 제47조, 제49조의2에 따라 취업할 수 있는 체류자격을 가진 외국인은 외국인등록 및 각종 체류허가 신청 시에 본인의 직업 및 연간 소득금액을 아래와 같이 관할 출입국·외국인관서에 신고하여야 합니다.…"
체류민원,,공통사항,체류자격외활동,기간,"유 의 사 항 > 체류자격외활동 > 1. 각종 체류허가 등에 관한 심사수수료 > 체류자격 변경허가, 체류자격외 활동허가, 근무처변경·추가허가(신고), 체류자격 부여허가, 체류기간 연장허가 신청 시",대표 코드 없음: 공통/부록 여부 검수 필요,"공통사항 / 1. 각종 체류허가 등에 관한 심사수수료 / 체류자격외활동 / 기간에 관한 정리입니다. 체류자격 변경허가, 체류자격외 활동허가, 근무처변경·추가허가(신고), 체류자격 부여허가, 체류기간 연장허가 신청 시; 직업 변경 시; 신고방법; 직업 : 각종 체류허가 신청 시 「외국인 직업 신고서」작성하여 제출; 연간 소득금액 : 각종 체류허가 신청 시 「통합신청서(신고서)」 ‘연 소득 금…"
체류민원,,공통사항,체류자격외활동,제출서류,유 의 사 항 > 체류자격외활동 > 1. 각종 체류허가 등에 관한 심사수수료 > 4 만6세 이상 만18세 이하 체류외국인의 재학증명서 제출 의무,대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 1. 각종 체류허가 등에 관한 심사수수료 / 체류자격외활동 / 제출서류에 관한 정리입니다. # 4 만6세 이상 만18세 이하 체류외국인의 재학증명서 제출 의무; 신고방법 : 각종 체류허가 신청 시 「통합신청서(신고서)」 ‘재학 여부’란에 재학 중인 학교명 등 기재하여 제출; 재학 중인 경우 재학증명서 등 재학 중임을 증명할 수 있는 서류 제출
체류민원,,공통사항,체류자격외활동,일반,"유 의 사 항 > 체류자격외활동 > 1. 각종 체류허가 등에 관한 심사수수료 > 8 장치·기계 조작 및 조립 종사자 Equipment, Machine Operating and Assembling Workers",대표 코드 없음: 공통/부록 여부 검수 필요; 주제 자동분류 약함: 검수 필요,"공통사항 / 1. 각종 체류허가 등에 관한 심사수수료 / 체류자격외활동 / 일반에 관한 정리입니다. # 8 장치·기계 조작 및 조립 종사자 Equipment, Machine Operating and Assembling Workers; [ ] 식품가공 관련 기계 조작직 Food Processing Related Machine Operating Occupations; [ ] 섬유 및 신발 관련…"
체류민원,,공통사항,외국인등록,대상,유 의 사 항 > 외국인등록 > 1. 각종 체류허가 등에 관한 심사수수료 > - 국내에 90일 초과하여 체류할 목적으로 사증을 신청하는 경우(전자사증 대상자의 경우에는 국내 입국 후 외국인등록 시 제출),대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 1. 각종 체류허가 등에 관한 심사수수료 / 외국인등록 / 대상에 관한 정리입니다. 국내에 90일 초과하여 체류할 목적으로 사증을 신청하는 경우(전자사증 대상자의 경우에는 국내 입국 후 외국인등록 시 제출); 출입국관리법 제10조의2 제1항 제2호(장기체류자격)를 의미(체류기간이 90일 이하 라도 장기체류자격 사증을 신청하는 경우 결핵진단서 제출 대상); 단기체류자격 중 계절근…
체류민원,,공통사항,전자사증,요건,유 의 사 항 > 전자사증 > 1. 각종 체류허가 등에 관한 심사수수료 > - 사증 신청 시 결핵진단서를 제출해야하는 외국인이 전자사증으로 입국한 경우,대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 1. 각종 체류허가 등에 관한 심사수수료 / 전자사증 / 요건에 관한 정리입니다. 사증 신청 시 결핵진단서를 제출해야하는 외국인이 전자사증으로 입국한 경우; 결핵고위험국가 국민이 장기체류 가능한 복수사증을 소지하고 사증 발급일로부터 6개월이 지나서 입국한 경우; 체류허가 신청 시; 단기체류자격으로 입국한 결핵고위험국가 국민이 장기체류자격으로 변경 신청하는 경우; 장기체류자격으로…
체류민원,,공통사항,전자사증,예외,유 의 사 항 > 전자사증 > 1. 각종 체류허가 등에 관한 심사수수료 > (출국행선지 확인이 불가한 경우 결핵진단서 제출을 원칙으로 하되 본인이 결핵 고위험 국가를 방문하지 않았음을 소명하는 경우 제출 면제 가능),대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 1. 각종 체류허가 등에 관한 심사수수료 / 전자사증 / 예외에 관한 정리입니다. (출국행선지 확인이 불가한 경우 결핵진단서 제출을 원칙으로 하되 본인이 결핵 고위험 국가를 방문하지 않았음을 소명하는 경우 제출 면제 가능)
체류민원,A-1,외교,전자사증,개요,"외교(A-1) > 전자사증 > - 외교(A-1), 공무(A-2), 협정(A-3) 자격 소지자",복수 코드 포함: 코드-규칙 연결 검수 필요,"외교(A-1) / - 외교(A-1), 공무(A-2), 협정(A-3) 자격 소지자 / 전자사증 / 개요에 관한 정리입니다. 외교(A-1), 공무(A-2), 협정(A-3) 자격 소지자; 만 6세 미만 소아(만 6세 이후 최초 체류허가 신청 시 제출) 및 임신부; 고령 또는 질병으로 거동이 불가능한 사람; 결핵 고위험국가(35개국); 네팔, 동티모르, 러시아, 말레이시아, 몽골, 미얀마, 방글라…"
체류민원,A-1,외교,체류자격외활동,활동범위,외교(A-1) > 체류자격외활동 > 자격 해당자 및 활동범위 1회에 부여할 수 있는 체류기간 상한 체류자격외 활동,표 구조에서 추출: 열/행 의미 검수 필요; 복수 코드 포함: 코드-규칙 연결 검수 필요; 여러 주제가 한 블록에 섞임: 분할 검수 필요,"외교(A-1) / 자격 해당자 및 활동범위 1회에 부여할 수 있는 체류기간 상한 체류자격외 활동 / 체류자격외활동 / 활동범위에 관한 정리입니다. 자격 해당자 및 활동범위 1회에 부여할 수 있는 체류기간 상한 체류자격외 활동; 대한민국정부가 접수한 외국정부의 외교사절단이나 영사기관의 구성원, 조약 또는 국제관행에 따라 외교사절과 동등한 특권과 면제를 받는 자와 그 가족; 재임기간; 취업허용…"
체류민원,A-1,외교,체류자격외활동,제한,"외교(A-1) > 체류자격외활동 > 다만, 「녹색기후기금(GCF)」 사무국 직원의 경우 배우자 및 미성년 자녀 외에 사무국 직원이 경제적으로 부양하고 있는 가계 구성원인 자녀도 체류자격외 활동 허용",복수 코드 포함: 코드-규칙 연결 검수 필요,"외교(A-1) / 체류자격외활동 / 제한에 관한 정리입니다. 다만, 「녹색기후기금(GCF)」 사무국 직원의 경우 배우자 및 미성년 자녀 외에 사무국 직원이 경제적으로 부양하고 있는 가계 구성원인 자녀도 체류자격외 활동 허용; 취업허용 범위; 기술연수(D-3), 비전문취업(E-9), 선원취업(E-10), 방문취업(H-2) 등 단순 노무 분야를 제외한 모든 체류자격에 해당하는 활동"
체류민원,A-2,공무,체류자격외활동,활동범위,공무(A-2) > 체류자격외활동 > 자격 해당자 및 활동범위 1회에 부여할 수 있는 체류기간 상한 체류자격외 활동,표 구조에서 추출: 열/행 의미 검수 필요; 복수 코드 포함: 코드-규칙 연결 검수 필요; 여러 주제가 한 블록에 섞임: 분할 검수 필요,"공무(A-2) / 자격 해당자 및 활동범위 1회에 부여할 수 있는 체류기간 상한 체류자격외 활동 / 체류자격외활동 / 활동범위에 관한 정리입니다. 자격 해당자 및 활동범위 1회에 부여할 수 있는 체류기간 상한 체류자격외 활동; 대한민국정부가 승인한 외국정부 또는 국제기구의 공무를 수행하는 자와 그 가족; 공무수행기간; 취업허용 국가 : ‘24. 1월 현재 29개 국가일본,스리랑카,방글라데시…"
체류민원,A-2,공무,체류자격외활동,대상,공무(A-2) > 체류자격외활동 > 적용대상,복수 코드 포함: 코드-규칙 연결 검수 필요,"공무(A-2) / 적용대상 / 체류자격외활동 / 대상에 관한 정리입니다. 적용대상; 대한민국과 협정을 체결하여 국내에 주소지를 둔 국제기구에서 공무(A-2) 자격으로 근무 중인 직원의 배우자 및 미성년 자녀; ※ 다만, 「녹색기후기금(GCF)」 사무국 직원의 경우 배우자 및 미성년 자녀 외에 사무국 직원이 경제적으로 부양하고 있는 가계 구성원인 자녀도 체류자격외 활동 허용; 취업허용 범위;…"
체류민원,A-2,공무,체류자격외활동,제출서류,공무(A-2) > 체류자격외활동 > 필수서류,표 구조에서 추출: 열/행 의미 검수 필요,"공무(A-2) / 체류자격외활동 / 제출서류에 관한 정리입니다. 신청서(별지 제34호 서식), 여권; 신청서(별지 제34호 서식), 여권; 출생증명서 등 신분관계 입증서류"
체류민원,A-3,협정,체류자격외활동,일반,협정(A-3) > 체류자격외활동 > 1. 국내 출생자,주제 자동분류 약함: 검수 필요,협정(A-3) / 체류자격외활동 / 일반에 관한 정리입니다. ### 1. 국내 출생자; 출생일로부터 90일 이내 신청; 90일 이내 출국하는 경우 별도허가 불필요
체류민원,A-3,협정,체류자격외활동,제출서류,협정(A-3) > 체류자격외활동 > 본인,표 구조에서 추출: 열/행 의미 검수 필요,"협정(A-3) / 체류자격외활동 / 제출서류에 관한 정리입니다. 신청서(별지34호), 여권; SPONSOR 복무확인서(현역) 또는 재직증명서(군속); 초청계약서(초청계약자)"
체류민원,A-3,협정,체류자격외활동,제출서류,협정(A-3) > 체류자격외활동 > 피부양가족,표 구조에서 추출: 열/행 의미 검수 필요,"협정(A-3) / 체류자격외활동 / 제출서류에 관한 정리입니다. 신청서(별지34호), 여권; 출생증명서 등 가족관계 입증서류; 부양자의 신분증명서; 초청계약자 등이 발급한 복무확인서·재직증명서 또는 초청계약서"
체류민원,A-3,협정,체류자격 변경,일반,협정(A-3) > 체류자격 변경 > 3. A-3소지자가 퇴직 등으로 자격 상실 후 국내에서 자격변경이 가능한 체류자격으로 계속 체류하고자 하는 경우 : 신분상실일로부터 30일 이내에 자격변경 신청 (30일 이내 출국하는 경우 별도 허가 불필요),주제 자동분류 약함: 검수 필요,협정(A-3) / 3. A-3소지자가 퇴직 등으로 자격 상실 후 국내에서 자격변경이 가능한 체류자격으로 계속 체류하고자 하는 경우 : 신분상실일로부터 30일 이내에 자격변경 신청 (30일 이내 출국하는 경우 별도 허가 불필요) / 체류자격 변경 / 일반에 관한 정리입니다. ### 3. A-3소지자가 퇴직 등으로 자격 상실 후 국내에서 자격변경이 가능한 체류자격으로 계속 체류하고자 하는 경우…
체류민원,A-3,협정,외국인등록,제출서류,협정(A-3) > 외국인등록 > 3. A-3소지자가 퇴직 등으로 자격 상실 후 국내에서 자격변경이 가능한 체류자격으로 계속 체류하고자 하는 경우 : 신분상실일로부터 30일 이내에 자격변경 신청 (30일 이내 출국하는 경우 별도 허가 불필요),표 구조에서 추출: 열/행 의미 검수 필요,협정(A-3) / 3. A-3소지자가 퇴직 등으로 자격 상실 후 국내에서 자격변경이 가능한 체류자격으로 계속 체류하고자 하는 경우 : 신분상실일로부터 30일 이내에 자격변경 신청 (30일 이내 출국하는 경우 별도 허가 불필요) / 외국인등록 / 제출서류에 관한 정리입니다. 외국인등록 면제 대상이나 본인이 원할 경우 외국인등록증 발급- 기타 등록외국인에게 부여 되는 각종 의무(등록사항변경 신…
체류민원,B-1,사증면제,,예외,사증면제(B-1) > 해 당 자,표 구조에서 추출: 열/행 의미 검수 필요,사증면제(B-1) / 예외에 관한 정리입니다. 해 당 자; 대한민국과 사증면제협정을 체결한 국가의 국민으로서 그 협정에 의한 활동을 하려는 자
체류민원,B-1,사증면제,체류자격 변경,기간,사증면제(B-1) > 체류자격 변경 > 체류자격변경 및 체류기간연장 목차,표 구조에서 추출: 열/행 의미 검수 필요,"사증면제(B-1) / 체류자격 변경 / 기간에 관한 정리입니다. 체류자격변경 및 체류기간연장 목차; 사증면제협정 또는 관광통과 목적으로 입국한 자에 대하여는 원칙적으로 체류기간 연장이나 체류자격 변경허가를 하지 아니하므로 체류기간이 협정기간 또는 법무부장관이 따로 정하는 기간을 초과하는 경우에는 반드시 사증을 발급 받아 입국하도록 안내; 제출서류; 신청서(34호 서식), 여권 원본, 수수료…"
체류민원,B-2,관광통과,체류자격 변경,기간,관광통과(B-2) > 체류자격 변경 > 체류자격변경 및 체류기간연장,표 구조에서 추출: 열/행 의미 검수 필요,"관광통과(B-2) / 체류자격 변경 / 기간에 관한 정리입니다. 체류자격변경 및 체류기간연장; 사증면제협정 또는 관광통과 목적으로 입국한 자에 대하여는 원칙적으로 체류기간 연장이나 체류자격 변경허가를 하지 아니하므로 체류기간이 협정기간 또는 법무부장관이 따로 정하는 기간을 초과하는 경우에는 반드시 사증을 발급 받아 입국하도록 안내 제출서류 ① 신청서(34호 서식), 여권 원본, 수수료 ② …"
체류민원,C-1,일시취재,,활동범위,일시취재(C-1) > 자격 해당자 및 활동범위,표 구조에서 추출: 열/행 의미 검수 필요,"일시취재(C-1) / 자격 해당자 및 활동범위 / 활동범위에 관한 정리입니다. 자격 해당자 및 활동범위; 외국의 신문,방송,잡지,기타 보도기관으로부터 파견되어 단기간 취재 · 보도활동을 하려는 자; 외국의 보도기관과의 계약에 의하여 단기간 취재 · 보도활동을 하려는 자; 외국 언론사의 지사설치 준비를 위해 단기간 취재 · 보도활동을 하려는 자"
체류민원,C-1,일시취재,체류기간 연장,기간,일시취재(C-1) > 체류기간 연장 > 체류기간 연장허가,표 구조에서 추출: 열/행 의미 검수 필요,"일시취재(C-1) / 체류기간 연장 / 기간에 관한 정리입니다. 체류기간 연장허가; 최장체류기간 : 90일; 입국일로부터 90일 미만 사증으로 입국한 자 또는 90일 미만 체류기간 받은 자에 대하여 입국일로부터 90일까지 연장; 제출서류; 신청서(34호 서식), 여권 원본, 수수료"

In [ ]:
# visa rows needing human review

manual_type,visa_code,visa_name_ko,petition_type,topic_type,source_section_path,review_notes,answer_summary
사증민원,,공통사항,사증발급,제출서류,유 의 사 항 > 사증발급,대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 사증발급 / 제출서류에 관한 정리입니다. 본 지침에서 주민등록등본 등 국내에서 발급·제출하는 서류의 유효기간은 별도의 유효기간이 설정되지 않은 경우 발급일로부터 3개월 이내임.
사증민원,,공통사항,사증발급,제한,유 의 사 항 > 사증발급 > 2. 신청인에 대한 직접 면담 필요 등 심사가 필요한 경우 대리 신청이 제한될 수 있음,대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 2. 신청인에 대한 직접 면담 필요 등 심사가 필요한 경우 대리 신청이 제한될 수 있음 / 사증발급 / 제한에 관한 정리입니다. 신청인에 대한 직접 면담 필요 등 심사가 필요한 경우 대리 신청이 제한될 수 있음
사증민원,,공통사항,사증발급,제출서류,유 의 사 항 > 사증발급 > 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함,대표 코드 없음: 공통/부록 여부 검수 필요,"공통사항 / 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 / 사증발급 / 제출서류에 관한 정리입니다. 신원보증서의 보증기간이 4년 이상인 때에도 4년을 한도로 하여 이를 인정하며, 각종 허가를 할 때의 허가기간은 신원보증서의 보증기간을 초과할 수 없음.; 주민등록등본·가족관계기록사항에 관한 증명서·사업자등록증·납세사실증…"
사증민원,,공통사항,사증발급,일반,공 통 사 항 > 사증발급 > 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함,대표 코드 없음: 공통/부록 여부 검수 필요; 주제 자동분류 약함: 검수 필요,공통사항 / 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 / 사증발급 / 일반에 관한 정리입니다. # 공 통 사 항; 외국인 결핵진단서 제출 의무 관련 안내; ※ 기타 자세한 사항은 하이코리아 홈페이지( www.hikorea.go.kr ) 공지사항 확인 바람.
사증민원,,공통사항,외국인등록,대상,공 통 사 항 > 외국인등록 > 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 > - 국내에 90일 초과하여 체류할 목적으로 사증을 신청하는 경우(전자사증 대상자의 경우에는 국내 입국 후 외국인등록 시 제출),대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 / 외국인등록 / 대상에 관한 정리입니다. 국내에 90일 초과하여 체류할 목적으로 사증을 신청하는 경우(전자사증 대상자의 경우에는 국내 입국 후 외국인등록 시 제출); 출입국관리법 제10조의2 제1항 제2호(장기체류자격)를 의미(체류기간이 90일 이하라도 장기체류…
사증민원,,공통사항,전자사증,요건,공 통 사 항 > 전자사증 > 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 > - 사증 신청 시 결핵진단서를 제출해야하는 외국인이 전자사증으로 입국한 경우,대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 / 전자사증 / 요건에 관한 정리입니다. 사증 신청 시 결핵진단서를 제출해야하는 외국인이 전자사증으로 입국한 경우; 결핵고위험국가 국민이 장기체류 가능한 복수사증을 소지하고 사증 발급일로부터 6개월이 지나서 입국한 경우; 체류허가 신청 시; 단기체류자격으로 입국한…
사증민원,,공통사항,전자사증,예외,공 통 사 항 > 전자사증 > 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 > (출국행선지 확인이 불가한 경우 결핵진단서 제출을 원칙으로 하되 본인이 결핵 고위험 국가를 방문하지 않았음을 소명하는 경우 제출 면제 가능),대표 코드 없음: 공통/부록 여부 검수 필요,공통사항 / 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 / 전자사증 / 예외에 관한 정리입니다. (출국행선지 확인이 불가한 경우 결핵진단서 제출을 원칙으로 하되 본인이 결핵 고위험 국가를 방문하지 않았음을 소명하는 경우 제출 면제 가능)
사증민원,,공통사항,전자사증,제한,공 통 사 항 > 전자사증 > 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 > ○ 적용 제외,복수 코드 포함: 코드-규칙 연결 검수 필요; 대표 코드 없음: 공통/부록 여부 검수 필요,"공통사항 / 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 / 전자사증 / 제한에 관한 정리입니다. ## ○ 적용 제외; 외교(A-1), 공무(A-2), 협정(A-3) 자격 소지자; 만 6세 미만 소아(만 6세 이후 최초 체류허가 신청 시 제출) 및 임신부; 고령 또는 질병으로 거동이 불가능한 사람"
사증민원,,공통사항,전자사증,일반,공 통 사 항 > 전자사증 > 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 > 결핵 고위험국가(35개국),대표 코드 없음: 공통/부록 여부 검수 필요; 주제 자동분류 약함: 검수 필요,"공통사항 / 3. 제출 서류 중 분량이 많은 서류는 이를 발췌하여 사용하는 등 필요 없는 서류를 제출하는 일이 없도록 하여야 함 / 전자사증 / 일반에 관한 정리입니다. ## ▣ 결핵 고위험국가(35개국); 네팔, 동티모르, 러시아, 말레이시아, 몽골, 미얀마, 방글라데시, 베트남, 태국, 스리랑카, 우즈베키스탄, 인도, 인도네시아, 중국, 캄보디아, 키르기스스탄, 파키스탄, 필리핀, 라오…"
사증민원,A-1,외교,사증발급,대상,외교(A-1) > 사증발급 > 해당자,표 구조에서 추출: 열/행 의미 검수 필요,"외교(A-1) / 해당자 / 사증발급 / 대상에 관한 정리입니다. 해당자; 외국정부의 외교사절단이나 영사기관의 구성원; 대한민국에 접수된 대사, 공사, 참사관, 서기관 등의 외교직원이 해당됨; 대한민국 정부에 접수된 총영사, 영사 등의 영사관(영사관이라 함은 그 자격에 있어 영사업무를 수행하는 자를 말함)이 해당됨; 조약 또는 국제관행에 따라 외교사절과 동등한 특권과 면제를 받은 자"
사증민원,A-1,외교,사증발급,대상,외교(A-1) > 사증발급 > 공관장 재량으로 발급할 수 있는 사증,표 구조에서 추출: 열/행 의미 검수 필요,"외교(A-1) / 사증발급 / 대상에 관한 정리입니다. 공관장 재량으로 발급할 수 있는 사증; 외교(A-1) 체류자격 사증발급; 외교(A-1) 자격 해당자에 대한 단수 또는 복수사증; 복수사증협정국가(미국, 일본, 중국, 러시아, 우즈베키스탄 등) 국민에 대해 그 협정에 따라 발급하는 복수사증; 일시적인 외교업무 수행자에게 발급하는 유효기간 3월의 단수사증(단, 우리 외교관에게 복수사증을 …"
사증민원,A-1,외교,사증발급,기간,외교(A-1) > 사증발급 > 2. 대한민국이 당사국인 국제기구의 직원·회의참가자에 대한 외교(A-1) 사증발급 기준 > 나. 사증발급 내용,복수 코드 포함: 코드-규칙 연결 검수 필요,외교(A-1) / 2. 대한민국이 당사국인 국제기구의 직원·회의참가자에 대한 외교(A-1) 사증발급 기준 / 사증발급 / 기간에 관한 정리입니다. 사증발급 내용; 외교(A-1)사증은 우리나라가 체결 또는 수락한 협정에서 명시적으로 외교특권을 규정하고 있는 국제기구 관계자에게만 발급; 우리나라에 주재할 예정인 국제기구 직원이 파견 · 재직증명서를 첨부하여 복수사증을 신청하는 경우에는 유효기간…
사증민원,A-1,외교,사증발급인정서,대상,외교(A-1) > 사증발급인정서 > 2. 대한민국이 당사국인 국제기구의 직원·회의참가자에 대한 외교(A-1) 사증발급 기준 > 사증발급인정서 발급대상,표 구조에서 추출: 열/행 의미 검수 필요,"외교(A-1) / 2. 대한민국이 당사국인 국제기구의 직원·회의참가자에 대한 외교(A-1) 사증발급 기준 / 사증발급인정서 / 대상에 관한 정리입니다. 사증발급인정서 발급대상; 국내 소재 국제기구의 직원, 회의참석자 등에 대한 사증발급인정서 발급; (사증발급인정서 발급) 국내에 소재한 국제기구 사무국 등의 직원과 관계인의 입국 편의를 위해 관할 출입국·외국인청(사무소·출장소)에서 사증발급인…"
사증민원,A-1,외교,사증발급인정서,참고,외교(A-1) > 사증발급인정서 > 2. 대한민국이 당사국인 국제기구의 직원·회의참가자에 대한 외교(A-1) 사증발급 기준 > 참고사항 ▶ 목차,표 구조에서 추출: 열/행 의미 검수 필요,외교(A-1) / 2. 대한민국이 당사국인 국제기구의 직원·회의참가자에 대한 외교(A-1) 사증발급 기준 / 사증발급인정서 / 참고에 관한 정리입니다. 참고사항 ▶ 목차; 외교관 여권을 소지하고 체류목적이 외교활동이어야 함; ※ 입국목적이 외교활동이 아닌 경우에는 그 목적에 합당한 체류자격의 사증을 발급 받아야 함
사증민원,A-2,공무,사증발급,활동범위,공무(A-2) > 사증발급 > 활동범위,표 구조에서 추출: 열/행 의미 검수 필요,공무(A-2) / 활동범위 / 사증발급 / 활동범위에 관한 정리입니다. 활동범위; 대한민국정부가 승인한 외국정부 또는 국제기구의 공무를 수행하는 자와 그 가족
사증민원,A-2,공무,사증발급,대상,공무(A-2) > 사증발급 > 해당자,표 구조에서 추출: 열/행 의미 검수 필요,공무(A-2) / 해당자 / 사증발급 / 대상에 관한 정리입니다. 해당자; 외국정부 또는 국제기구의 공무를 수행하는 자; 대한민국 정부가 승인한 외국정부 외교사절단의 사무직원 및 기술직원과 노무직원; 대한민국정부가 승인한 영사기관의 사무직원 및 기술직원과 노무직원; 대한민국에 본부를 둔 국제기구의 직원
사증민원,A-2,공무,사증발급,기간,공무(A-2) > 사증발급 > 공관장 재량으로 발급할 수 있는 사증,표 구조에서 추출: 열/행 의미 검수 필요,공무(A-2) / 사증발급 / 기간에 관한 정리입니다. 공관장 재량으로 발급할 수 있는 사증; 공무(A-2) 체류자격 사증발급; 공무(A-2)의 체류자격에 해당하는 자에 대한 단수사증; 외국정부 또는 국제기구의 공무수행자(가족 및 수행원 포함)에 대한 30일 이하 외교(A-1) 또는 공무(A-2) 체류자격에 해당하는 단수사증; 우리나라에서 주재 근무하고자 하는 국제연합 및 산하기관의 직원과…
사증민원,A-2,공무,사증발급인정서,대상,공무(A-2) > 사증발급인정서 > 2. 대한민국이 당사국인 국제기구의 직원·회의참가자에 대한 공무(A-2) 사증발급 기준 > 사증발급인정서 발급대상,표 구조에서 추출: 열/행 의미 검수 필요; 복수 코드 포함: 코드-규칙 연결 검수 필요,"공무(A-2) / 2. 대한민국이 당사국인 국제기구의 직원·회의참가자에 대한 공무(A-2) 사증발급 기준 / 사증발급인정서 / 대상에 관한 정리입니다. 사증발급인정서 발급대상; 체류자격의 유효기간 3년의 복수사증 발급; 단, 가족에 대한 외교(A-1)사증 발급은 협정에 규정한 대상에게만 발급함이 원칙; 동반가족이 타국적자이거나 일반여권 소지자인 경우에도 해당 국제기구 등의 정식 공한을 제출…"
사증민원,A-2,공무,체류자격외활동,참고,공무(A-2) > 체류자격외활동 > 2. 대한민국이 당사국인 국제기구의 직원·회의참가자에 대한 공무(A-2) 사증발급 기준 > 참고사항 ➡ 목차,표 구조에서 추출: 열/행 의미 검수 필요; 복수 코드 포함: 코드-규칙 연결 검수 필요,"공무(A-2) / 2. 대한민국이 당사국인 국제기구의 직원·회의참가자에 대한 공무(A-2) 사증발급 기준 / 체류자격외활동 / 참고에 관한 정리입니다. 참고사항 ➡ 목차; 관용여권을 소지하고 아국 입국목적이 공무수행이어야 함; 발급기준 및 적용에 대하여는 외교사증 발급기준에 준함; 외교(A-1), 공무(A-2) 자격으로 근무중인 국제기구 직원의 동반가족 중 배우자 및 미성년자녀에 대해 체류…"
사증민원,A-2,공무,체류자격외활동,일반,공무(A-2) > 체류자격외활동 > 1) 「대한민국과 녹색기후기금 간의 녹색기후기금의 본부에 관한 협정」 제 13조 제7항,주제 자동분류 약함: 검수 필요,공무(A-2) / 1) 「대한민국과 녹색기후기금 간의 녹색기후기금의 본부에 관한 협정」 제 13조 제7항 / 체류자격외활동 / 일반에 관한 정리입니다. 「대한민국과 녹색기후기금 간의 녹색기후기금의 본부에 관한 협정」 제 13조 제7항
사증민원,A-3,협정,사증발급,대상,협정(A-3) > 사증발급 > 해당자,표 구조에서 추출: 열/행 의미 검수 필요,협정(A-3) / 해당자 / 사증발급 / 대상에 관한 정리입니다. 해당자; 협정에 의하여 외국인등록이 면제 또는 면제할 필요가 있다고 인정되는 자; 상기자의 가족
사증민원,A-3,협정,사증발급,제출서류,협정(A-3) > 사증발급 > 공관장 재량으로 발급할 수 있는 사증,표 구조에서 추출: 열/행 의미 검수 필요,"협정(A-3) / 사증발급 / 제출서류에 관한 정리입니다. 사증발급신청서 (별지 제17호 서식), 여권, 표준규격사진 1매, 수수료; 파견, 재직을 증명하는 서류 또는 해당국 외교부장관이나 소속부처 장관의 공한(공무수행임을 입증하는 내용 명시); 체류기간 및 유효기간은 한미교류재단 협조공한 상의 '장학금 수혜기간'"
사증민원,A-3,협정,사증발급,참고,협정(A-3) > 사증발급 > 참고사항 목차,표 구조에서 추출: 열/행 의미 검수 필요,협정(A-3) / 사증발급 / 참고에 관한 정리입니다. 참고사항 목차; 대한민국 정부가 체결한 협정이나 합의각서 등에 사증발급에 관한 규정이 있는 때 또는 법무부장관이 호혜원칙 등을 고려하여 따로 정하는 때에는 그에 따라 사증발급(시행규칙 제13조 제1항); 사증발급대상자가 복수사증발급협정 등이 체결된 국가의 국민이라 하더라도 특별한 사유가 있는 때에는 단수사증발급 가능(시행규칙 제13조 …
사증민원,B-1,사증면제,사증발급,제한,"사증면제(B-1) > 사증발급 > C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 > 취업 활동 제외",표 구조에서 추출: 열/행 의미 검수 필요,"사증면제(B-1) / C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 / 사증발급 / 제한에 관한 정리입니다. 취업 활동 제외; 라이베리아, 방글라데시, 싱가포르, 태국, 터키, 파키스탄, 바베이도스, 칠레, 콜롬비아, 페루, 노르웨이, 덴마크, 스웨덴, 아이슬란드, 영국, 포르투갈…"
사증민원,B-1,사증면제,사증발급,제한,"사증면제(B-1) > 사증발급 > C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 > 영리활동 제외",표 구조에서 추출: 열/행 의미 검수 필요,"사증면제(B-1) / C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 / 사증발급 / 제한에 관한 정리입니다. 영리활동 제외; 그리스, 독일, 리히텐슈타인, 스위스, 스페인, 프랑스, 헝가리, 튀니지"
사증민원,B-1,사증면제,사증발급,제한,"사증면제(B-1) > 사증발급 > C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 > 영리, 취업 활동 제외",표 구조에서 추출: 열/행 의미 검수 필요,"사증면제(B-1) / C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 / 사증발급 / 제한에 관한 정리입니다. 영리, 취업 활동 제외; 이스라엘, 그레나다, 니카라과, 도미니카연방, 바하마, 베네수엘라, 세인트빈센트그레나딘, 세인트키츠네비스, 세인트루시아, 아이티, 앤티가바부다, 엘…"
사증민원,B-1,사증면제,사증발급,제한,"사증면제(B-1) > 사증발급 > C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 > 제한없음",표 구조에서 추출: 열/행 의미 검수 필요,"사증면제(B-1) / C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 / 사증발급 / 제한에 관한 정리입니다. 제한없음; 멕시코, 수리남, 네덜란드, 룩셈부르크, 벨기에, 에스토니아, 오스트리아, 이탈리아, 핀란드"
사증민원,B-1,사증면제,사증발급인정서,대상,"사증면제(B-1) > 사증발급인정서 > C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 > 사증발급인정서 발급대상",표 구조에서 추출: 열/행 의미 검수 필요,"사증면제(B-1) / C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 / 사증발급인정서 / 대상에 관한 정리입니다. 사증발급인정서 발급대상; 사증면제(B-1), 관광통과(B-2) 자격은 사증발급인정서 발급 제외대상임"
사증민원,B-1,사증면제,사증발급인정서,참고,"사증면제(B-1) > 사증발급인정서 > C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 > 참고사항",표 구조에서 추출: 열/행 의미 검수 필요; 복수 코드 포함: 코드-규칙 연결 검수 필요,"사증면제(B-1) / C-3(단기방문) 활동범위를 기본으로 하되 협정에 따라 제외되는 활동은 할 수 없으며, 협정에서 제외되는 활동을 하고자 입국하고자 할 때는 사증을 받아야 함 / 사증발급인정서 / 참고에 관한 정리입니다. 참고사항; 입국심사시 체류자격 및 체류기간; 체류자격; 외교 · 관용여권소지자 : 외교(A-1), 공무(A-2); 외교관 여권을 소지하고 외교활동, 공무수행 차 입국하…"
사증민원,B-1,사증면제,사증발급인정서,일반,사증면제(B-1) > 사증발급인정서 > 나. 일반여권소지자 : 사증면제(B-1) > 아 시 아 주,표 구조에서 추출: 열/행 의미 검수 필요; 주제 자동분류 약함: 검수 필요,"사증면제(B-1) / 나. 일반여권소지자 : 사증면제(B-1) / 사증발급인정서 / 일반에 관한 정리입니다. 아 시 아 주; 라 오 스; 외교, 관용; 일; '09.06.26."

In [ ]:
# stay D-8/E-7/F-6 focus rows

manual_type,visa_code,visa_name_ko,petition_type,topic_type,applicant_context,answer_summary,needs_human_review
체류민원,D-8,기업투자,체류자격외활동,제출서류,,"기업투자(D-8) / 체류자격외활동 / 제출서류에 관한 정리입니다. 신청서(별지34호 서식) 여권 및 외국인등록증, 표준규격사진1장, 수수료 ②파견명령서(본사 발행) ③원근무처와 동일계열사 입증서류(법인등기사항전부증명서 원본 등) ④사업자등록증 사본 ⑤외국기업의 국내지사설치 신고(허가)관련 서류(지사 설치허가서 등) ⑥원근무처장의 동의서 ⑦영업실적증명 서류 -법인 납세사실증명원 등",false
체류민원,D-8,기업투자,체류자격외활동,제출서류,,"기업투자(D-8) / 체류자격외활동 / 제출서류에 관한 정리입니다. 신청서(별지 34호 서식), 여권 및 외국인등록증, 수수료 ②총(학)장의 추천서 ③고유번호증(사업자등록증)사본 ④고용계약서 원본 및 사본 ⑤원근무처장의 동의서",true
체류민원,D-8,기업투자,체류자격외활동,개요,,"기업투자(D-8) / 체류자격외활동 / 개요에 관한 정리입니다. (시행규칙 제49조의 2); 문화예술(D-1), 유학(D-2), 일반연수(D-4) 내지 무역경영(D-9) 자격 소지자는 소속기관 또는 단체의 변경(명칭변경 포함); 구직(D-10) 자격 소지자는 연수 개시 사실 또는 연수기관의 변경(명칭 변경 포함); 방문취업(H-2) 자격 소지자는 개인·기관·단체 또는 업체에 최초로 고용된 …",true
체류민원,D-8,기업투자,외국인등록,제출서류,※ 주재(D-7) 내지 무역경영(D-9)자격 소지자의 같은 계열회사내의 이동일 경우 아래 서류를 징구하여 ' 외국인등록사항 변동신고 '로 업무처리,"기업투자(D-8) / ※ 주재(D-7) 내지 무역경영(D-9)자격 소지자의 같은 계열회사내의 이동일 경우 아래 서류를 징구하여 ' 외국인등록사항 변동신고 '로 업무처리 / 외국인등록 / 제출서류에 관한 정리입니다. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장, 수수료 ② 파견명령서 원본(외국 본사발행) ③동일계열사 입증서류(법인등기사항전부증명서 등) ③추가 변경근무처의…",false
체류민원,D-8,기업투자,외국인등록,예외,1. 사종면제(B-1) 자격으로 입국한 독일인 에 대한 장기체류자격으로 변경,"기업투자(D-8) / 1. 사종면제(B-1) 자격으로 입국한 독일인 에 대한 장기체류자격으로 변경 / 외국인등록 / 예외에 관한 정리입니다. ### 1. 사종면제(B-1) 자격으로 입국한 독일인 에 대한 장기체류자격으로 변경; 허가체류자격 : 기술연수(D-3), 비전문취업(E-9) 및 관광취업(H-1)을 제외한 모든 장기체류자격",true
체류민원,D-8,기업투자,체류자격 변경,개요,,"기업투자(D-8) / 체류자격 변경 / 개요에 관한 정리입니다. ### 2. 기업투자(D-8)자격 소지자의 동일계열 외국기업의 주재(D-7)자격으로의 자격변경 허가; <!-- layout: planning; This is semantically a table used to present requirements for status change.; Side-by-side check: No, i…",false
체류민원,D-8,기업투자,체류자격 변경,제출서류,"4. Columns: Col 1: Label (e.g., 대상, 제출서류), Col 2: Description/List.","기업투자(D-8) / 4. Columns: Col 1: Label (e.g., 대상, 제출서류), Col 2: Description/List. / 체류자격 변경 / 제출서류에 관한 정리입니다. Columns: Col 1: Label (e.g., 대상, 제출서류), Col 2: Description/List.; Merge cell detection: None.; Header structure…",false
체류민원,D-8,기업투자,체류자격 변경,대상,"4. Columns: Col 1: Label (e.g., 대상, 제출서류), Col 2: Description/List.","기업투자(D-8) / 4. Columns: Col 1: Label (e.g., 대상, 제출서류), Col 2: Description/List. / 체류자격 변경 / 대상에 관한 정리입니다. 대상; 기업투자(D-8) 자격을 소지하고 외국인투자기업에 필수전문인력으로 근무하고 있는 자로 동일계열 외국기업에서 설치한 국내지사, 자회사, 주재사무소, 법무부장관이 정하는 계열회사 등에 파견(전근)명령…",true
체류민원,D-8,기업투자,외국인등록,제출서류,"4. Columns: Col 1: Label (e.g., 대상, 제출서류), Col 2: Description/List.","기업투자(D-8) / 4. Columns: Col 1: Label (e.g., 대상, 제출서류), Col 2: Description/List. / 외국인등록 / 제출서류에 관한 정리입니다. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장,수수료; 파견명령서(외국본사 발행) 원본 또는 재직예정증명서; 외국기업의 국내지사 설치허가서 사본 또는 연락사무소 설치",true
체류민원,D-8,기업투자,,대상,기업투자(D-8),"기업투자(D-8) / 대상에 관한 정리입니다. # 기업투자(D-8); 자격 해당자 및 활동범위 1. 「외국인투자촉진법」에 따른 외국인투자기업 대한민국 법인의 경영·관리 또는 생산·기술 분야에 종사하려는 필수 전문인력[이하 ‘법인에 투자(D-8-1)’로 구분]; 설립완료 법인만 해당, 국내에서 채용하는 사람은 제외; 지식재산권을 보유하는 등 우수한 기술력으로 「벤처기업육성에 관한 특별조치법」…",false
체류민원,D-8,기업투자,,기간,,기업투자(D-8) / 기간에 관한 정리입니다. 체류기간 상한; 법인에 투자(D-8-1) 및 개인기업에 투자(D-8-3); 벤처투자(D-8-2) 및 기술창업(D-8-4); 년,true
체류민원,D-8-1,기업투자,,요건,- 법인에 투자(D-8-1) 및 개인기업에 투자(D-8-3) 자격요건을 갖춘 등록외국인,기업투자(D-8-1) / - 법인에 투자(D-8-1) 및 개인기업에 투자(D-8-3) 자격요건을 갖춘 등록외국인 / 요건에 관한 정리입니다. 법인에 투자(D-8-1) 및 개인기업에 투자(D-8-3) 자격요건을 갖춘 등록외국인,false
체류민원,D-8-1,기업투자,체류자격 변경,제출서류,① 법인에 투자(D-8-1),"기업투자(D-8-1) / ① 법인에 투자(D-8-1) / 체류자격 변경 / 제출서류에 관한 정리입니다. 법인에 투자(D-8-1); 사증발급 및 체류자격 변경 신청 시 제출서류 기준 준용; ※ 단, “④-1 기술창업(D-8-4)-㉮ 점수제 적용 대상자”의 경우 학력 요건 증빙 서류 면제",true
체류민원,D-8,기업투자,체류자격 변경,절차,"1. 제목자격의활동하기 변제법의 확대(제목관리과-325, '09.06.15.)","기업투자(D-8) / 1. 제목자격의활동하기 변제법의 확대(제목관리과-325, '09.06.15.) / 체류자격 변경 / 절차에 관한 정리입니다. # 1. 제목자격의활동하기 변제법의 확대(제목관리과-325, '09.06.15.); 원래의 제목족적을 입해하지 않은 법의 내에서 정규교육기관(초·중·고 및 대학)의 교육을 받고자 하는 때는 제목기간 변의 내에서 별도의 허가 절차 불요.(09.6.…",false
체류민원,D-8,기업투자,체류자격 변경,일반,2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동,"기업투자(D-8) / 2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동 / 체류자격 변경 / 일반에 관한 정리입니다. ## 2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동; (제목정 과-402, 2007.06.20.)",true
체류민원,D-8,기업투자,체류자격외활동,활동범위,2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동,기업투자(D-8) / 2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동 / 체류자격외활동 / 활동범위에 관한 정리입니다. 활동범위; 대학에서 90일 이내 강의활동을 하려는 자에 대한 단기취업(C-4-5)자격으로의 자격외 활동,true
체류민원,D-8,기업투자,체류자격외활동,개요,2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동,"기업투자(D-8) / 2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동 / 체류자격외활동 / 개요에 관한 정리입니다. 대 상; 투자자 등(D-7, D-8, D-9)의 자격 소지자 중 국내기업(투자기업포함)에서 상근이사 이상의 직으로 근무하는 자; 전문인력(E-1, E-3 E-5, E-7) 자격소지자",true
체류민원,D-8,기업투자,체류자격외활동,제출서류,2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동,기업투자(D-8) / 2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동 / 체류자격외활동 / 제출서류에 관한 정리입니다. 공(학)장의 추천 ③교유법호공(사업자등록증)사본 ④교용 제자사원본 및 사본 ⑤법근무자정의 동의서,true
체류민원,D-8,기업투자,체류자격외활동,요건,2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동,"기업투자(D-8) / 2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동 / 체류자격외활동 / 요건에 관한 정리입니다. ### 1. 허가요건; 법인에 투자(D-8-1); 투자대상이 대한민국 법인일 것; 투자금액이 1억원 이상으로, 투자한 법인의 의결권 있는 주식중우의 100분의 10이상 소유(우국인투자자정법 제2조제1항1호)하여야 하며 법인의 주식 등을 소유하되 입원 과정, 심의 제…",false
체류민원,D-8,기업투자,체류자격외활동,대상,2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동,"기업투자(D-8) / 2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동 / 체류자격외활동 / 대상에 관한 정리입니다. i) 점주에 적용 대상자; 국내에서 전문학자 이상의 학위를 취득한 사람, 또는 국외에서 학사 이상의 학위를 취득한 사람",false
체류민원,D-8,기업투자,체류자격외활동,점수,2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동,기업투자(D-8) / 2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동 / 체류자격외활동 / 점수에 관한 정리입니다. 사람일 것; 점수제에 따라 총 300점 중 60점 이상의 점수를 득점하였을 것; 필수항목은 반드시 1개 이상 충족하여야 함; 대한민국 법인을 설립하고 법인등기 및 사업자등록을 완료하였을 것,false
체류민원,D-8,기업투자,체류자격외활동,대상,2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동,"기업투자(D-8) / 2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동 / 체류자격외활동 / 대상에 관한 정리입니다. ii) 점수제 적용 면제자(기술창업 특례 대상자); K-Startup 그랜드챌린지 참여자로서 아래 요건을 모두 갖춘 자; 최근 2년 이내 K-Startup 그랜드챌린지 참여자로서 선발되어 사업화지원을 받고 있거나, 지원을 받은 사실이 있는 자; 중기부 초청으로 K-…",false
체류민원,D-8,기업투자,체류자격외활동,개요,2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동,"기업투자(D-8) / 2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동 / 체류자격외활동 / 개요에 관한 정리입니다. 기술연수(D-3), 비전문취업(E-9), 선원취업(E-10), 방문취업(H-2), 기타(G-1), 관광취업(H-1) 자격으로 입국한 아일랜드, 프랑스, 영국인(다른 나라 국민은 가능)",true
체류민원,D-8,기업투자,체류자격 변경,대상,2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동,"기업투자(D-8) / 2. 외국인투자기업 CEO 등 우수전문인력의 대한 강정활동 / 체류자격 변경 / 대상에 관한 정리입니다. 투자자가 아닌 자를 임원으로 등재 뒤, 해당외국인의 체류자격변경을 신청하는 경우 이들은 외국투자기업에서 파견된 자 또는 개인투자자에 포함되지 아니하고 외국인 투자기업이 국내에서 직접 채용하는 경우에 해당하므로 특정활동(E-7) 자격 대상임",true
체류민원,D-8,기업투자,체류자격 변경,개요,,"기업투자(D-8) / 체류자격 변경 / 개요에 관한 정리입니다. 기업투자(D-8) 자격으로 변경이 허용되지 않는 자격은 원칙적으로 자격변경을 허용하지 않되, 투자의 진정성이 인정되는 등 특별한 사유가 있는 경우 (투자금액이 3억 이상 고액이거나 상당한 투자실적이 있는 경우 등)에는 정밀심사 후 관할 지방출입국·외국인관서의 장 권한으로 자격변경 허용 (가급적 3억 미만 소액투자자는 출국 후 …",false
체류민원,D-8,기업투자,외국인등록,제출서류,,"기업투자(D-8) / 외국인등록 / 제출서류에 관한 정리입니다. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격 사진1장; 사업자등록증 사본, 법인등기사항전부증명서, 주주변동 상황명세서 원본; 투자기업등록증 사본; 주재활동의 경우 파견명령서(파견기간이 명시된 해외 본사 및 해외 본사의 제3국 소재 지사 발행) 및 재직증명서; 투자자금 도입관련 입증서류",false
체류민원,D-8,기업투자,외국인등록,대상,- 해당국 세관이나 본국 은행 (금융기관)의 외화반출허가(신고)서 (해당자),"기업투자(D-8) / - 해당국 세관이나 본국 은행 (금융기관)의 외화반출허가(신고)서 (해당자) / 외국인등록 / 대상에 관한 정리입니다. 해당국 세관이나 본국 은행 (금융기관)의 외화반출허가(신고)서 (해당자); 투자자금 도입 내역서 (송금확인증, 외국환 매입증명서, 세관신고서 등); 나) 현물출자의 경우; 현물출자완료 확인서 사본(관세청장 발행); 세관 수입신고필증 사본",false
체류민원,D-8,기업투자,외국인등록,제출서류,,"기업투자(D-8) / 외국인등록 / 제출서류에 관한 정리입니다. 《투자금액 3억원 미만 개인투자자에 대한 추가서류》⑨ 자본금 사용내역 입증서류 (물품구매 영수증, 사무실 인테리어 비용, 국내은행 계좌 입출금 내역서 등)⑩ 해당 업종 또는 분야의 사업 경험 관련 국적국 서류 (필요시 징구)",true
체류민원,D-8,기업투자,외국인등록,제출서류,,기업투자(D-8) / 외국인등록 / 제출서류에 관한 정리입니다. 외국인투자기업등록지위를 갖춘 금융지주회사에서 100%출자한 자회사의 필수전문인력인 경우 제출서류,false
체류민원,D-8,기업투자,외국인등록,제출서류,"1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장","기업투자(D-8) / 1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장 / 외국인등록 / 제출서류에 관한 정리입니다. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장; 금융지주회사의 인가서 및 외국인투자기업등록증; 자회사의 법인등기사항전부증명서 및 주주명부(금융지주회사가 100% 출자한 자회사임을 입증하는 서류); 금융지주회사 및 자회사의 사업자등록증…",false
체류민원,D-8,기업투자,외국인등록,제출서류,"1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장","기업투자(D-8) / 1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장 / 외국인등록 / 제출서류에 관한 정리입니다. 신청서(별지34호 서식), 여권, 외국인등록증(해당자), 표준규격사진1장; 사업자등록증 사본, 법인등기사항전부증명서; 벤처기업 관련 서류- 벤처기업확인서 또는 예비벤처기업확인서; 지식재산권을 보유하는 등 우수한 기술력을 가지고 있음을 입증하는 서류- 특…",true
체류민원,D-8,기업투자,외국인등록,제출서류,"1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장","기업투자(D-8) / 1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장 / 외국인등록 / 제출서류에 관한 정리입니다. 신청서(별지34호 서식), 여권, 외국인등록증(해당자), 표준규격사진1장; 공동사업자가 표시된 사업자등록증 사본, 공동사업자약정서 원본; 투자기업등록증 사본; 공동사업자인 국민의 사업자금(사용 내역) 입증서류; 주재활동의 경우 파견명령서(파견기간이 명시…",true
체류민원,D-8,기업투자,외국인등록,대상,"1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장","기업투자(D-8) / 1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장 / 외국인등록 / 대상에 관한 정리입니다. 해당국 세관이나 본국 은행 (금융기관)의 외화반출허가 (신고)서 (해당자); 투자자금 도입 내역서 (송금확인증, 외국환 매입증명서, 세관신고서 등); ㉯ 현물출자의 경우; 현물출자완료 확인서 사본(관세청장 발행); 세관 수입신고필증 사본",false
체류민원,D-8,기업투자,외국인등록,제출서류,"1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장","기업투자(D-8) / 1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장 / 외국인등록 / 제출서류에 관한 정리입니다. 자본금 사용내역 입증서류 (물품구매 영수증, 사무실 인테리어 비용, 국내은행 계좌 입출금 내역서 등)- 해당 업종 또는 분야의 사업 경험 관련 국적국 서류 (필요시 징구)",true
체류민원,D-8,기업투자,외국인등록,제출서류,"1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장","기업투자(D-8) / 1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장 / 외국인등록 / 제출서류에 관한 정리입니다. > - 신청서, 여권, 표준규격 사진, 체류지 입증서류(부동산 임대차 계약서 등); > - 법인등기사항전부증명서 및 사업자등록증 사본; > - 법인 설립이 완료되지 않은 경우에는 법인등기사항전부증명서 및 사업자등록증 사본 제출을 생략가능하며, 6개월 이…",false
체류민원,D-8,기업투자,외국인등록,제출서류,"1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장","기업투자(D-8) / 1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장 / 외국인등록 / 제출서류에 관한 정리입니다. 지식재산권 보유(등록)자는 특허증·실용신안등록증·디자인등록증 사본",false
체류민원,D-8,기업투자,외국인등록,제출서류,"1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장","기업투자(D-8) / 1. 신청서(별지34호 서식), 여권 및 외국인등록증, 표준규격사진1장 / 외국인등록 / 제출서류에 관한 정리입니다. OECD 국가 지식재산권 보유(등록)자는 그 사실을 입증할 수 있는 서류 사본(아포스티유 확인을 원칙으로 하되, 미가입 국가 국민은 OECD 국가 주재 대한민국 영사 확인으로 갈음); 특허 등 출원자는 특허청장 발행 출원사실증명서; 법무부장관이 지정한 …",false
체류민원,D-8,기업투자,체류자격 변경,제출서류,나. 점수제 적용 면제 대상자(기술창업 특례 대상자) 제출서류,"기업투자(D-8) / 나. 점수제 적용 면제 대상자(기술창업 특례 대상자) 제출서류 / 체류자격 변경 / 제출서류에 관한 정리입니다. (K-Startup 그랜드 챌린지 참여자) 기본 제출서류 + 중기부 발행 K-startup 그랜드챌린지 참여 확인서, 중기부장관 추천 공문 (확인서 및 추천서는 최초 체류자격변경허가 시에만 징구)",false
체류민원,E-7,특정활동,,활동범위,활동범위 및 해당자,특정활동(E-7) / 활동범위 및 해당자 / 활동범위에 관한 정리입니다. 활동범위 및 해당자; 대한민국 내의 공·사기관 등과의 계약에 따라 법무부장관이 특별히 지정하는 활동에 종사하려고 하는 사람,true
체류민원,E-7,특정활동,,기간,,"특정활동(E-7) / 기간에 관한 정리입니다. 회에 부여할 수 있는 체류기간 상한; [ ] 3년(주무부처 추천 우수인재, 지역특화발전특구 및 첨단의료복합단지 내 E-7 직종 종사자, 경제자유구역 내 의료연구개발기관의 연구원에 대해서는 5년)",true
체류민원,E-7,특정활동,,대상,적용대상 및 도입기준 등,특정활동(E-7) / 적용대상 및 도입기준 등 / 대상에 관한 정리입니다. 적용대상 및 도입기준 등; 적용대상 [출입국관리법 시행령 별표 1의2 20. 특정활동(E-7)]; [ ] 대한민국 내의 공·사기관 등과의 계약에 따라 법무부장관이 특별히 지정하는 활동에 종사하려는 사람; ‘특정활동’이란 법무부장관이 국가경쟁력 강화 등을 위해 전문적인 지식·기술 또는 기능을 가진 외국인력 도입이 특히…,true
체류민원,E-7,특정활동,,요건,2. 도입직종 선정 및 관리 등,"특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 요건에 관한 정리입니다. ## 2. 도입직종 선정 및 관리 등; (직종 선정) 중앙부처를 대상으로 정기 또는 수시로 전문외국인력 도입이 필요한 신규 직종 수요조사 등을 실시하고, 외국인력 도입의 필요성 및 효과, 국민대체성 등을 종합 검토하여 선정; 수요조사 시 직종별 학력 및 경력요건, 고용업체 요건 등에 관한 의견도 수렴하고, 체…",false
체류민원,E-7,특정활동,,요건,2. 도입직종 선정 및 관리 등,특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 요건에 관한 정리입니다. ### 가. 자격요건; (일반요건) 다음 요건 중 하나를 충족하여야 함; 도입직종과 연관성이 있는 분야의 석사 이상 학위 소지; 도입직종과 연관성이 있는 학사학위 소지 + 1년 이상의 해당분야 경력; 산업발전법 제5조에 따라 산업통상자원부장관이 고시하는 '첨단기술' 분야,false
체류민원,E-7,특정활동,,요건,2. 도입직종 선정 및 관리 등,"특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 요건에 관한 정리입니다. (국내 전문대학졸업(예정)자) 전공과목과 관련이 있는 도입허용 직종에 취업하는 경우 1년 이상의 경력요건을 면제하고, 고용의 필요성 등이 인정되면 허용; ※ 다만, 고등교육법 제2조 제1호제4호에 해당하는 대학에서 학위를 취득한 경우에만 적용; (국내 대학 졸업(예정) 학사이상 학위 소지자) 도입허용 직종에 …",false
체류민원,E-7,특정활동,,대상,2. 도입직종 선정 및 관리 등,특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 대상에 관한 정리입니다. 추천대상자 요건; 동종 5년 이상 경력; 학사 + 1년 이상 경력; 석사 이상; 국내 학위취득자는 해당 분야 경력 불요,true
체류민원,E-7,특정활동,,대상,2. 도입직종 선정 및 관리 등,"특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 대상에 관한 정리입니다. 추천대상 직종; KOTRA : IT, 기술경영, 나노, 디지털 전자, 바이오, 수송 및 기계, 신소재, 환경 및 에너지 등 8개 분야(공·사 기관)",true
체류민원,E-7,특정활동,사증발급인정서,요건,2. 도입직종 선정 및 관리 등,특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 사증발급인정서 / 요건에 관한 정리입니다. (특정 일본인 소프트웨어 기술자 등) 일본정보처리개발협회소속 중앙정보교육연구소(CAIT) 및 정보처리기술자시험센터(JITEC)가 인정하는 소프트웨어개발기술자와 기본정보기술자 자격증을 소지한 일본인에 대해서는 자격기준과 무관하게 사증발급인정서 발급 등 허용,false
체류민원,E-7,특정활동,사증발급인정서,대상,2. 도입직종 선정 및 관리 등,특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 사증발급인정서 / 대상에 관한 정리입니다. ## 적용대상 및 도입기준 등; (부처추천 전문능력 구비 우수인재) 연간 총 수령보수가 전년도 1인당 국민총소득(GNI)의 1.5배 이상이고 소관 중앙행정기관의 장(경제자유구역의 지정 및 운영에 관한 특별법 또는 지역특화발전특구에 대한 규제특례법 등의 적용을 받는 경우에는 관할 특별시장·광역…,true
체류민원,E-7,특정활동,체류자격 변경,요건,2. 도입직종 선정 및 관리 등,특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 체류자격 변경 / 요건에 관한 정리입니다. ## 나. 도입 방법; (원칙) 기업 스스로 채용이 필요한 분야의 전문 외국인력을 발굴하여 자격검증 등을 거쳐 채용한 후 사증발급을 신청하거나 체류자격 변경허가 등을 신청하면 법무부에서 결격여부 등을 심사하여 허용여부 결정; (뿌리산업체 숙련기능공 등) 체류자격 변경허가 요건을 갖춘 비전문취…,false
체류민원,E-7,특정활동,체류자격 변경,대상,2. 도입직종 선정 및 관리 등,"특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 체류자격 변경 / 대상에 관한 정리입니다. 개별 직종별 심사기준에서 고용추천서 발급 대상 및 발급 부처 등을 정하고 있음(근거 영 제7조제3,4항)",false
체류민원,E-7,특정활동,체류자격 변경,요건,2. 도입직종 선정 및 관리 등,특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 체류자격 변경 / 요건에 관한 정리입니다. (필수) 직종별 심사기준에서 고용추천서 징구가 “필수” 사항으로 규정된 경우에는 접수 시 반드시 추천서가 첨부되어야 함,false
체류민원,E-7,특정활동,체류자격 변경,예외,2. 도입직종 선정 및 관리 등,특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 체류자격 변경 / 예외에 관한 정리입니다. (면제) 다음에 해당하는 경우는 고용추천서 징구 면제; 대학 및 공공기관에서 고용하고자 하는 경우; 사기업이라도 대기업 관리자에 해당하는 자를 고용하는 경우,false
체류민원,E-7,특정활동,체류자격 변경,추천,2. 도입직종 선정 및 관리 등,특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 체류자격 변경 / 추천에 관한 정리입니다. (전자고용추천서 시스템 운영) 대한민국 비자포털(visa.go.kr)에 전문인력 고용추천을 위한 전자고용추천시스템 운영,false
체류민원,E-7,특정활동,체류자격외활동,제출서류,2. 도입직종 선정 및 관리 등,특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 체류자격외활동 / 제출서류에 관한 정리입니다. (공통 첨부서류) 체류자격 변경 또는 체류자격외 활동허가 등 신청 시에도 적정하게 준용,false
체류민원,E-7,특정활동,체류자격외활동,요건,2. 도입직종 선정 및 관리 등,"특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 체류자격외활동 / 요건에 관한 정리입니다. 피초청(외국인)인 준비서류 : 여권사본, 반명함판 칼라사진 1매, 고용계약서, 자격요건 입증서류(학위증, 경력증명서, 자격증 등); ※ 국외에서 발급한 서류는 반드시 국문 또는 영문 번역본 첨부, 주요핵심 서류에 대해서는 영사 공증 또는 아포스티유 확인서 제출; 초청인 준비 서류 : 고용단체…",false
체류민원,E-7,특정활동,체류자격외활동,제한,2. 도입직종 선정 및 관리 등,특정활동(E-7) / 2. 도입직종 선정 및 관리 등 / 체류자격외활동 / 제한에 관한 정리입니다. 신원보증서(법무부 장관이 고시한 근무처변경·추가 신고가 제한되는 직종의 종사자만 해당),false
체류민원,E-7,특정활동,체류자격외활동,요건,○ (자격요건) 특정활동(E-7) 자격 외국인을 고용할 수 있도록 허용된 직종의 업체나 단체 등의 대표로서 아래 경우에 모두 해당하지 않아야 함,특정활동(E-7) / ○ (자격요건) 특정활동(E-7) 자격 외국인을 고용할 수 있도록 허용된 직종의 업체나 단체 등의 대표로서 아래 경우에 모두 해당하지 않아야 함 / 체류자격외활동 / 요건에 관한 정리입니다. (자격요건) 특정활동(E-7) 자격 외국인을 고용할 수 있도록 허용된 직종의 업체나 단체 등의 대표로서 아래 경우에 모두 해당하지 않아야 함,false
체류민원,E-7,특정활동,체류자격외활동,대상,○ (자격요건) 특정활동(E-7) 자격 외국인을 고용할 수 있도록 허용된 직종의 업체나 단체 등의 대표로서 아래 경우에 모두 해당하지 않아야 함,특정활동(E-7) / ○ (자격요건) 특정활동(E-7) 자격 외국인을 고용할 수 있도록 허용된 직종의 업체나 단체 등의 대표로서 아래 경우에 모두 해당하지 않아야 함 / 체류자격외활동 / 대상에 관한 정리입니다. 출입국관리법 시행규칙 제17조의3 제2항 제1호 내지 제7호에 규정된 사중발급인정서 발급제한 대상자에 해당하는 경우; 허용직종별 고용업체 요건이나 업체당 외국인 고용허용 인원 및 …,false
체류민원,E-7,특정활동,사증발급인정서,대상,○ (자격요건) 특정활동(E-7) 자격 외국인을 고용할 수 있도록 허용된 직종의 업체나 단체 등의 대표로서 아래 경우에 모두 해당하지 않아야 함,"특정활동(E-7) / ○ (자격요건) 특정활동(E-7) 자격 외국인을 고용할 수 있도록 허용된 직종의 업체나 단체 등의 대표로서 아래 경우에 모두 해당하지 않아야 함 / 사증발급인정서 / 대상에 관한 정리입니다. (심사기준) 사증발급인정서 발급 제한대상인지 여부, 고용업체 요건 충족 및 정상 운영 여부, 저임금 활용여부 등을 종합 심사; (창업 초기 소규모 외국인투자기업 또는 벤처기업) 제…",false
체류민원,E-7,특정활동,체류자격외활동,예외,1. 체류자격외활동허가 면제범위 확대,특정활동(E-7) / 1. 체류자격외활동허가 면제범위 확대 / 체류자격외활동 / 예외에 관한 정리입니다. ## 1. 체류자격외활동허가 면제범위 확대; 원래의 체류목적을 침해하지 않은 범위 내에서 정규교육기관(초·중·고 및 대학)의 교육을 받고자 하는 때는 체류기간 범위 내에서 별도의 허가 절차 불요('09.6.15.부 시행),false
체류민원,E-7,특정활동,체류자격외활동,활동범위,1. 체류자격외활동허가 면제범위 확대,특정활동(E-7) / 1. 체류자격외활동허가 면제범위 확대 / 체류자격외활동 / 활동범위에 관한 정리입니다. 활동범위; 대학에서 90일 이내 강의활동을 하려는 자에 대한 단기취업(C-4-5)자격으로의 자격외 활동,true
체류민원,E-7,특정활동,체류자격외활동,대상,1. 체류자격외활동허가 면제범위 확대,"특정활동(E-7) / 1. 체류자격외활동허가 면제범위 확대 / 체류자격외활동 / 대상에 관한 정리입니다. 대상; 투자자 등(D-7, D-8, D-9)의 자격 소지자 중 국내기업(투자기업포함)에서 상근이사 이상의 직으로 근무하는 자; 전문인력(E-1, E-3 E-5, E-7) 자격소지자",true
체류민원,E-7,특정활동,외국인등록,제출서류,1. 체류자격외활동허가 면제범위 확대,"특정활동(E-7) / 1. 체류자격외활동허가 면제범위 확대 / 외국인등록 / 제출서류에 관한 정리입니다. 신청서(별지 34호 서식), 여권 및 외국인등록증, 수수료 ②주무부처 장의 고용추천서 ③사업자등록증 사본 ④고용계약서 ⑤원 근무처장의 동의서",true
체류민원,E-7,특정활동,체류자격외활동,참고,3. “주한외국공관원 가족”의 국내취업은 상호주의에 따라 외교부장관(외교사절담당관)의 추천을 받은 자에 한하여 체류자격외 활동허가,특정활동(E-7) / 3. “주한외국공관원 가족”의 국내취업은 상호주의에 따라 외교부장관(외교사절담당관)의 추천을 받은 자에 한하여 체류자격외 활동허가 / 체류자격외활동 / 참고에 관한 정리입니다. ## 3. “주한외국공관원 가족”의 국내취업은 상호주의에 따라 외교부장관(외교사절담당관)의 추천을 받은 자에 한하여 체류자격외 활동허가; 취업허용 국가 : '18. 6월 현재 27개 국가; 일본…,true
체류민원,E-7,특정활동,체류자격외활동,개요,"4. ""A-1, A-2 소지자"" 에 대한 자격외활동 허가 범위(청장, 사무소장, 출장소장 위임)","특정활동(E-7) / 4. ""A-1, A-2 소지자"" 에 대한 자격외활동 허가 범위(청장, 사무소장, 출장소장 위임) / 체류자격외활동 / 개요에 관한 정리입니다. ""A-1, A-2 소지자"" 에 대한 자격외활동 허가 범위(청장, 사무소장, 출장소장 위임); 취업허용 범위; 외국어회화강사(E-2), 외국인학교교사(E-7), 외국어교열요원(E-7)으로의 활동, 문화예술(D-1), 종교(D-6)…",true
체류민원,E-7,특정활동,체류자격외활동,추천,"4. ""A-1, A-2 소지자"" 에 대한 자격외활동 허가 범위(청장, 사무소장, 출장소장 위임)","특정활동(E-7) / 4. ""A-1, A-2 소지자"" 에 대한 자격외활동 허가 범위(청장, 사무소장, 출장소장 위임) / 체류자격외활동 / 추천에 관한 정리입니다. 외교부(외교사절담당관)에서 받은 고용추천서 필수; 해당 자격 입증 서류 : 해당 체류 자격의 자격외활동서류; 고액투자외국인 및 전문인력 배우자에 대한 취업; 허용대상; 고급과학기술인력(SCIENCE 카드) 및 첨단기술인력(GOL…",true
체류민원,E-7,특정활동,체류자격외활동,제한,"단순노무(D-3, E-9) 등을 제외한 모든 직종에 대한 체류자격외 활동허가","특정활동(E-7) / 단순노무(D-3, E-9) 등을 제외한 모든 직종에 대한 체류자격외 활동허가 / 체류자격외활동 / 제한에 관한 정리입니다. 단순노무(D-3, E-9) 등을 제외한 모든 직종에 대한 체류자격외 활동허가; 허가기간 : 배우자의 체류기간까지(계속연장 가능)",false
체류민원,E-7,특정활동,체류자격외활동,제출서류,라. 제출서류 : 규칙 제76조에 의한 체류자격별 첨부서류(신원보증서 생략),특정활동(E-7) / 라. 제출서류 : 규칙 제76조에 의한 체류자격별 첨부서류(신원보증서 생략) / 체류자격외활동 / 제출서류에 관한 정리입니다. 제출서류 : 규칙 제76조에 의한 체류자격별 첨부서류(신원보증서 생략),true
체류민원,E-7,특정활동,체류자격외활동,추천,라. 제출서류 : 규칙 제76조에 의한 체류자격별 첨부서류(신원보증서 생략),"특정활동(E-7) / 라. 제출서류 : 규칙 제76조에 의한 체류자격별 첨부서류(신원보증서 생략) / 체류자격외활동 / 추천에 관한 정리입니다. 주무부처 장의 고용추천서 또는 고용필요성 입증서류 ③ 고용계약서 ④ 사업자등록증 ⑤ 학위증 또는 자격증; 방문동거(F-1), 동반(F-3)자격 소지자의 외국어회화강사(E-2), 외국인학교교사(E-7)로의 자격외 활동",true
체류민원,E-7,특정활동,외국인등록,수수료,라. 제출서류 : 규칙 제76조에 의한 체류자격별 첨부서류(신원보증서 생략),"특정활동(E-7) / 라. 제출서류 : 규칙 제76조에 의한 체류자격별 첨부서류(신원보증서 생략) / 외국인등록 / 수수료에 관한 정리입니다. 신청서(별지 34호 서식), 여권 및 외국인등록증, 수수료; 고용계약서 ③ 사업자등록증 ④ 해당국교원 자격증 원본(교원자격증이 없는 경우 '학위증 및 경력증명서') ⑤범죄경력증명서(E-2 자격요건과 동일) ⑥채용신체검사서(E-2 자격요건과 동일) ⑦…",true
체류민원,E-7,특정활동,외국인등록,수수료,라. 제출서류 : 규칙 제76조에 의한 체류자격별 첨부서류(신원보증서 생략),"특정활동(E-7) / 라. 제출서류 : 규칙 제76조에 의한 체류자격별 첨부서류(신원보증서 생략) / 외국인등록 / 수수료에 관한 정리입니다. 신청서(별지 34호 서식), 여권 및 외국인등록증, 수수료; 고용계약서 ③ 사업자등록증 사본 ④ 추천서(해당 기관장); 학위증(원본 및 사본)",false
체류민원,E-7,특정활동,체류자격외활동,예외,9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례,"특정활동(E-7) / 9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례 / 체류자격외활동 / 예외에 관한 정리입니다. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례; 국제학교의 보조교사, 강사, 보조사감, 행정사무원; (자격요건) 국제학교 재학생 부모나 교직원의 직계 가족, 18세 이상 해외 본교 졸업생으로서 학사 이상 학위 소지 또는 해당분야 2년 이상 근무경력 또는 TE…",false
체류민원,E-7,특정활동,체류자격외활동,요건,9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례,"특정활동(E-7) / 9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례 / 체류자격외활동 / 요건에 관한 정리입니다. (자격요건) 영어를 모국어로 사용하는 국가 국민인 국제학교 재학생 부모나 교직원의 가족, 18세 이상 해외 본교 졸업생은 별도 자격요건 없이 허용; 단, 영어를 모국어로 사용하지 않는 국가의 국민인 재학생 부모나 교직원의 가족, 해외 본교 졸업생에 대해서는 공인영어…",false
체류민원,E-7,특정활동,체류자격외활동,대상,9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례,"특정활동(E-7) / 9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례 / 체류자격외활동 / 대상에 관한 정리입니다. 사전 허가대상; 기계공학기술자(2351), 제도사(2395), 해외영업원(2742) 중 해외 온라인상품판매원, 디자이너(285), 판매사무원(31215), 주방장 및 조리사(441), 고객상담사무원(3991), 호텔접수사무원(3922), 의료코디네이터(S3922),…",false
체류민원,E-7,특정활동,체류자격외활동,일반,9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례,특정활동(E-7) / 9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례 / 체류자격외활동 / 일반에 관한 정리입니다. ## ➡ '10.11.15.부 사후 신고제로 개정(출입국관리법시행령 제26조의2제1항); 전문인력 활용도 제고를 통한 국가경쟁력 강화차원에서 전문인력에 대해서는 기존 사전허가를 사후신고만으로 근무처를 변경·추가할 수 있도록 제도 개선,true
체류민원,E-7,특정활동,체류자격외활동,일반,9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례,특정활동(E-7) / 9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례 / 체류자격외활동 / 일반에 관한 정리입니다. ### 《법무부고시 제11-510》; 주방장 및 조리사의 경우 원 근무처 외 타 근무처에서의 근무시간은 원 근무처 근무시간의 1/3을 초과하지 못함,true
체류민원,E-7,특정활동,외국인등록,요건,9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례,특정활동(E-7) / 9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례 / 외국인등록 / 요건에 관한 정리입니다. ### 가. 자격요건; 판매사무원 등 14개 직종을 제외한 특정활동(E-7) 자격 소지자로서 외국인등록을 하고 체류하고 있는 자로 변경·추가되는 근무처에서 활동하는데 필요한 자격요건을 구비하고 있는 자,false
체류민원,E-7,특정활동,외국인등록,요건,9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례,특정활동(E-7) / 9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례 / 외국인등록 / 요건에 관한 정리입니다. 자격요건을 갖추었더라도 본인 귀책사유로 해고 또는 중도 퇴직한 자로서 원고용주의 이적동의를 받지 못한 자는 제외,false
체류민원,E-7,특정활동,사증발급인정서,절차,9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례,특정활동(E-7) / 9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례 / 사증발급인정서 / 절차에 관한 정리입니다. ### 나. 신고절차 등; 신고사유 발생일로부터 15일 이내에 관할 출입국·외국인청(사무소·출장소)장에게 신고(대리인의 신고 허용); 여권에 근무처변경·추가신고 스티커나 신고인을 부착 또는 날인·기재하여야 하기 때문에 방문신고를 원칙으로 함; 선의의 고용주 보호와 …,false
체류민원,E-7,특정활동,외국인등록,제출서류,9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례,"특정활동(E-7) / 9. 제주영어교육도시 종사자에 대한 체류자격외활동허가 특례 / 외국인등록 / 제출서류에 관한 정리입니다. 통합신청서[별지 제34호제34호의2 서식], 여권 및 외국인등록증, 수수료 없음 ②주무부처 장의 고용추천서 또는 고용의 필요성을 입증하는 서류 ③ 고용계약약서 ④원 근무처 장의 동의서 ⑤고용계약서 ⑥사업자등록증; ※ 사유서와 신원보증서는 원칙적으로 제출 생략; 원 …",false

In [ ]:
# visa D-8/E-7/F-6 focus rows

manual_type,visa_code,visa_name_ko,petition_type,topic_type,applicant_context,answer_summary,needs_human_review
사증민원,D-8,기업투자,사증발급,제한,,"기업투자(D-8) / 사증발급 / 제한에 관한 정리입니다. # 기업투자(D-8); 「외국인투자촉진법」에 따른 외국인투자기업 대한민국 법인의 경영·관리 또는 생산·기술 분야에 종사하려는 필수 전문인력 [이하 '법인에 투자(D-8-1)'로 구분]; 설립완료 법인만 해당, 국내에서 채용하는 사람은 제외; 지식재산권을 보유하는 등 우수한 기술력으로 「벤처 기업육성에 관한 특별조치법」 제2조의2제1…",false
사증민원,D-8,기업투자,사증발급,활동범위,활동범위 및 해당자,"기업투자(D-8) / 활동범위 및 해당자 / 사증발급 / 활동범위에 관한 정리입니다. 활동범위 및 해당자; 「외국인투자촉진법」에 따른 외국인투자기업인 대한민국 국민(개인)이 경영하는 기업의 경영·관리 또는 생산·기술 분야에 종사하려는 필수전문인력 [이하 '개인기업에 투자(D-8-3)'로 구분]; 국내에서 채용하는 사람은 제외; 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 국외에서 학…",false
사증민원,D-8,기업투자,사증발급,기간,,"기업투자(D-8) / 사증발급 / 기간에 관한 정리입니다. 체류기간의 상한; 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 국외에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 법인 창업자 : 2년 (단, 스타트업 코리아 특별비자 대상자 중 법인 미설립자는 6개월)",false
사증민원,D-8-1,기업투자,사증발급,대상,1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외),기업투자(D-8-1) / 1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외) / 사증발급 / 대상에 관한 정리입니다. ### 1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외),false
사증민원,D-8,기업투자,사증발급,요건,1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외),"기업투자(D-8) / 1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외) / 사증발급 / 요건에 관한 정리입니다. 기본요건; 투자대상이 대한민국 법인(설립완료 법인만 해당) 일 것; 투자금액이 1억원 이상으로, 투자한 법인의 의결권 있는 주식총수의 100분의 10이상을 소유(외국인투자촉진법시행령 제2조제2항1호…",false
사증민원,D-8,기업투자,사증발급,예외,1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외),"기업투자(D-8) / 1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외) / 사증발급 / 예외에 관한 정리입니다. 명의 반입 및 대리송금은 예외적으로 인정(단, 투자금 3억원 이상 투자자의 경우 부모 및 배우자 부모 명의 반입 및 대리 송금 추가 인정 가능)",false
사증민원,D-8,기업투자,사증발급,절차,1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외),"기업투자(D-8) / 1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외) / 사증발급 / 절차에 관한 정리입니다. 신청기관; 원칙적으로 신청자의 본국에 소재한 대한민국 공관; ※ 단, 신청인이 해외에 주재하며 사업체 등을 운영(영주권 소지 등 장기거주자 포함)하고 있을 경우에는 주재하고 있는 국가 소재 재외공관…",false
사증민원,D-8,기업투자,사증발급,수수료,1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외),"기업투자(D-8) / 1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외) / 사증발급 / 수수료에 관한 정리입니다. 사증발급신청서 (별지 제17호 서식), 여권, 표준규격사진 1매, 수수료; 주재활동의 경우 파견명령서(파견기간 명시) 및 재직증명서; 외국인투자기업등록증 사본; 사업자등록증 사본, 법인등기사항전부…",false
사증민원,D-8,기업투자,사증발급,대상,1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외),"기업투자(D-8) / 1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외) / 사증발급 / 대상에 관한 정리입니다. 해당국 세관이나 본국 은행 (금융기관)의 외화반출허가(신고)서 (해당자); 투자자금 도입 내역서 (송금확인증, 외국환 매입증명서, 세관신고서 등); ㉯ 현물출자의 경우; 현물출자완료 확인서 사본(관…",false
사증민원,D-8,기업투자,사증발급,제출서류,1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외),"기업투자(D-8) / 1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외) / 사증발급 / 제출서류에 관한 정리입니다. 자본금 사용내역 입증서류 (물품구매 영수증, 사무실 인테리어 비용, 국내은행 계좌 입출금 내역서 등); 사업장 존재 입증 서류 (사무실 임대차 계약서, 사업장 전경·사무공간·간판 사진 등 자료)",false
사증민원,D-8,기업투자,사증발급,제출서류,1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외),"기업투자(D-8) / 1. 외국인투자촉진법의 규정에 의한 「외국인 투자기업에서의 주재활동」 해당자에 대한 기업투자(D-8-1) 사증발급 (특정국가 제외) / 사증발급 / 제출서류에 관한 정리입니다. ※ 재외공관의 장은 입국목적, 초청의 진정성, 초청자 및 피초청자의 자격 확인 등을 심사하기 위해 필요한 경우 첨부서류를 일부 가감할 수 있음",false
사증민원,D-8,기업투자,사증발급,요건,"2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 등에 대한 기업투자(D-8-2) 사증발급 (중국, 특정국가 제외)","기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 등에 대한 기업투자(D-8-2) 사증발급 (중국, 특정국가 제외) / 사증발급 / 요건에 관한 정리입니다. ## 가. 기본요건; 지식재산권을 보유하는 등 우수한 기술력으로 「벤처기업육성에 관한 특별조치법」 제2조의2제1항제2호다목에 따른 벤처기업을 설립(또는 설립예비)한 사람 중 같은 법 제25조에 따라…",false
사증민원,D-8,기업투자,사증발급,일반,"2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 등에 대한 기업투자(D-8-2) 사증발급 (중국, 특정국가 제외)","기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 등에 대한 기업투자(D-8-2) 사증발급 (중국, 특정국가 제외) / 사증발급 / 일반에 관한 정리입니다. 공관장 재량으로 발급할 수 있는 사증; 기술평가보증기업 및 예비벤처기업(해당 벤처기업의 법인설립 또는 사업자등록을 준비 중인 경우 및 동 기업의 창업 후 6개월 이내의 기업)도 해당; 벤처기업 또는…",true
사증민원,D-8,기업투자,사증발급,절차,"2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 등에 대한 기업투자(D-8-2) 사증발급 (중국, 특정국가 제외)","기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 등에 대한 기업투자(D-8-2) 사증발급 (중국, 특정국가 제외) / 사증발급 / 절차에 관한 정리입니다. ## 나. 신청기관; 원칙적으로 신청자의 본국에 소재한 대한민국 공관; ※ 단, 신청인이 해외에 주재하며 사업체 등을 운영(영주권 소지 등 장기거주자 포함)하고 있을 경우에는 주재하고 있는 국가 소…",false
사증민원,D-8,기업투자,사증발급,수수료,"2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 등에 대한 기업투자(D-8-2) 사증발급 (중국, 특정국가 제외)","기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 등에 대한 기업투자(D-8-2) 사증발급 (중국, 특정국가 제외) / 사증발급 / 수수료에 관한 정리입니다. 사증발급신청서 (별지 제17호 서식), 여권사본, 표준규격사진 1매, 수수료; 사업자등록증 사본, 법인등기사항전부증명서; 벤처기업확인서 또는 예비벤처기업확인서; 지식재산권을 보유하는 등 우수한 기…",false
사증민원,D-8,기업투자,사증발급,요건,3. 국민이 경영하는 기업에 투자하는 외국인에 대한 기업투자(D-8-3) 자격 사증발급,"기업투자(D-8) / 3. 국민이 경영하는 기업에 투자하는 외국인에 대한 기업투자(D-8-3) 자격 사증발급 / 사증발급 / 요건에 관한 정리입니다. ## 가. 기본요건; 투자대상이 대한민국 국민(개인)이 경영하는 기업일 것; 투자금액이 1억원 이상으로, 투자한 기업의 출자총액의 100분의 10이상을 소유 (외국인투자촉진법시행령 제2조제2항1호)하고 사업자등록증상 한국인과 공동대표로 등재될…",false
사증민원,D-8,기업투자,사증발급,수수료,3. 국민이 경영하는 기업에 투자하는 외국인에 대한 기업투자(D-8-3) 자격 사증발급,"기업투자(D-8) / 3. 국민이 경영하는 기업에 투자하는 외국인에 대한 기업투자(D-8-3) 자격 사증발급 / 사증발급 / 수수료에 관한 정리입니다. 사증발급신청서 (별지 제17호 서식), 여권, 표준규격사진 1매, 수수료; 외국인투자기업등록증 사본; 공동사업자인 국민의 사업자금(사용 내역) 입증서류; 공동사업자가 표시된 사업자등록증 사본, 공동사업자약정서 원본; 투자자금 도입관련 입증서류",false
사증민원,D-8,기업투자,사증발급,제출서류,3. 국민이 경영하는 기업에 투자하는 외국인에 대한 기업투자(D-8-3) 자격 사증발급,"기업투자(D-8) / 3. 국민이 경영하는 기업에 투자하는 외국인에 대한 기업투자(D-8-3) 자격 사증발급 / 사증발급 / 제출서류에 관한 정리입니다. 자본금 사용내역 입증서류 (물품구매 영수증, 사무실 인테리어 비용, 국내은행 계좌 입출금 내역서 등); 사업장 존재 입증 서류 (사무실 임대차 계약서, 사업장 전경·사무공간·간판 사진 등 자료)",false
사증민원,D-8,기업투자,사증발급,요건,"4. 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 국외에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급","기업투자(D-8) / 4. 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 국외에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급 / 사증발급 / 요건에 관한 정리입니다. ## 가. 기본요건; 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 외국에…",false
사증민원,D-8,기업투자,사증발급,일반,"4. 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 국외에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급","기업투자(D-8) / 4. 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 국외에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급 / 사증발급 / 일반에 관한 정리입니다. ## 공관장 재량으로 발급할 수 있는 사증; 지식재산권을 보유하거나 이에 준하는…",true
사증민원,D-8,기업투자,사증발급,절차,"4. 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 국외에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급","기업투자(D-8) / 4. 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 국외에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급 / 사증발급 / 절차에 관한 정리입니다. ### 나. 신청기관; 원칙적으로 신청자의 본국에 소재한 대한민국 공관; ※ 단…",false
사증민원,D-8,기업투자,사증발급,수수료,"4. 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 국외에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급","기업투자(D-8) / 4. 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 국외에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급 / 사증발급 / 수수료에 관한 정리입니다. 사증발급신청서 (별지 제17호 서식), 여권, 표준규격사진 1매, 수수료; 법…",false
사증민원,D-8-4S,기업투자,사증발급,개요,"4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급","기업투자(D-8-4S) / 4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급 / 사증발급 / 개요에 관한 정리입니다. # 4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급",false
사증민원,D-8,기업투자,사증발급,요건,"4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급","기업투자(D-8) / 4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급 / 사증발급 / 요건에 관한 정리입니다. ### 가. 기본요건; 스타트업 코리아 특별비자 추천 민간평가위원회의 심사 승인을 받은 자",false
사증민원,D-8,기업투자,체류자격 변경,일반,"4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급","기업투자(D-8) / 4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급 / 체류자격 변경 / 일반에 관한 정리입니다. 중소벤처기업부장관으로부터 기술창업 체류자격 변경허가 또는 사증발급을 위한 추천을 받았을 것",true
사증민원,D-8,기업투자,체류자격 변경,제출서류,"4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급","기업투자(D-8) / 4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급 / 체류자격 변경 / 제출서류에 관한 정리입니다. 단, 법인설립이 완료되지 않은 경우에는 법인등기사항전부증명서 및 사업자등록증 사본 제출 생략 가능하며, 입국 후 체류기간(6개월) 이내에 법인등기사항전부증명서 및 사업자등록…",false
사증민원,D-8,기업투자,체류자격 변경,절차,"4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급","기업투자(D-8) / 4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급 / 체류자격 변경 / 절차에 관한 정리입니다. ## 나. 신청기관; 원칙적으로 신청자의 본국에 소재한 대한민국 공관; 단, 신청인이 해외에 주재하며 사업체 등을 운영(영주권 소지 등 장기거주자 포함)하고 있을 경우에는 주재…",false
사증민원,D-8,기업투자,사증발급,제출서류,"4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급","기업투자(D-8) / 4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급 / 사증발급 / 제출서류에 관한 정리입니다. 사증발급신청서 (별지 제17호 서식), 여권, 표준규격사진 1매; 법인등기사항전부증명서 및 사업자등록증 사본 (제출 가능 시); 스타트업 코리아 특별비자 추천서 (중소벤처기업부 …",false
사증민원,D-8,기업투자,사증발급,제출서류,"4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급","기업투자(D-8) / 4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급 / 사증발급 / 제출서류에 관한 정리입니다. 재외공관의 장은 입국목적, 초청의 진정성, 초청자 및 피초청자의 자격 확인 등을 심사하기 위해 필요한 경우 첨부서류를 일부 가감할 수 있음",false
사증민원,D-8,기업투자,사증발급,기간,5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급,기업투자(D-8) / 5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급 / 사증발급 / 기간에 관한 정리입니다. # 5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급; 기업투자(D-8) 자격에 해당하는 입증서류를 제출하지 못하는 경우라도 단기상용(C-3-4) 자격에 해당하는 때에는 단기상용사증발급,false
사증민원,D-8,기업투자,사증발급,대상,5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급,기업투자(D-8) / 5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급 / 사증발급 / 대상에 관한 정리입니다. ## 가. 대상자; 기업대표 (협정 제2조 다호); 러시아 국가의 법령 또는 법인·개인기업의 설립 문서(정관)에 따라 대한민국의 영역에서 실체에 대한 통제나 관리를 수행하는 자,false
사증민원,D-8,기업투자,사증발급,제출서류,5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급,"기업투자(D-8) / 5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급 / 사증발급 / 제출서류에 관한 정리입니다. 사증발급인정신청서 (별지 제21호 서식), 여권사본, 표준규격사진 1매; 파견명령서(파견기간 명시) 또는 재직증명서; 외국인 투자신고서 또는 투자기업등록증 사본; 등기부등본 및 사업자등록증 사본; 대리인 신청시 : 위임장, 대리인 재직증명서, …",false
사증민원,D-8,기업투자,사증발급,제출서류,5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급,"기업투자(D-8) / 5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급 / 사증발급 / 제출서류에 관한 정리입니다. 출입국·외국인청(사무소·출장소)장은 초청의 진정성, 초청자 및 피초청자의 자격 확인 등을 심사하기 위해 필요한 경우 첨부서류를 일부 가감할 수 있음",false
사증민원,D-8,기업투자,사증발급,대상,5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급,기업투자(D-8) / 5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급 / 사증발급 / 대상에 관한 정리입니다. ## 가. 대상자; 외국 자본 참여 사업체의 대표 또는 전문직원 (협정 제3조 가호); 대한민국의 영역에서 상업활동을 수행하는 외국 자본 참여 사업체의 대표 또는 전문직원인 우즈베키스탄 국민기업대표 (협정 제2조 다호),false
사증민원,D-8,기업투자,사증발급,제출서류,5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급,"기업투자(D-8) / 5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급 / 사증발급 / 제출서류에 관한 정리입니다. ※ 출입국·외국인청(사무소·출장소)장은 초청의 진정성, 초청자 및 피초청자의 자격 확인 등을 심사하기 위해 첨부서류의 일부를 가감할 수 있음",false
사증민원,D-8,기업투자,사증발급,요건,5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급,"기업투자(D-8) / 5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급 / 사증발급 / 요건에 관한 정리입니다. ## 가. 기본요건; 투자대상이 대한민국 법인 일 것; 투자금액이 1억원 이상으로, 투자한 법인의 의결권 있는 주식총수의 100분의 10이상을 소유(외국인투자촉진법시행령 제2조제2항1호)하거나 법인의 주식 등을 소유하면서 임원 파견, 선임 계약 등…",false
사증민원,D-8,기업투자,사증발급,제출서류,5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급,"기업투자(D-8) / 5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급 / 사증발급 / 제출서류에 관한 정리입니다. 사증발급인정신청서 (별지 제21호 서식), 여권, 표준규격사진 1매; 주재활동의 경우 파견명령서(파견기간 명시) 및 재직증명서; 외국인투자기업등록증 사본; 사업자등록증 사본, 법인등기사항전부증명서, 주주변동상황명세서 원본; 투자자금 도입관련 입…",false
사증민원,D-8,기업투자,사증발급,제출서류,5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급,"기업투자(D-8) / 5. 칠레인에 대하여는 한·칠레 자유무역협정에 따라 체류기간 1년의 단수사증 발급 / 사증발급 / 제출서류에 관한 정리입니다. 자본금 사용내역 입증서류 (물품구매 영수증, 사무실 인테리어 비용, 국내은행 계좌 입출금 내역서 등); 사업장 존재 입증 서류 (사무실 임대차 계약서, 사업장 전경·사무공간·간판 사진 등 자료); 대리인 신청시 : 위임장, 대리인 재직증명서, …",false
사증민원,D-8,기업투자,사증발급,일반,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급 / 일반에 관한 정리입니다. ## 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,true
사증민원,D-8,기업투자,사증발급,요건,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급 / 요건에 관한 정리입니다. ### 가. 기본요건; 지식재산권을 보유하는 등 우수한 기술력으로 「벤처 기업육성에 관한 특별조치법」 제2조의2제1항제2호다목에 따른 벤처기업을 설립(또는 설립예비)한 사람 중 같은 법 제25조에 따라 벤처기업 확인(또는 예비 벤처…,false
사증민원,D-8,기업투자,사증발급,제출서류,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,"기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급 / 제출서류에 관한 정리입니다. 사증발급인정신청서 (별지 제21호 서식), 여권사본, 표준규격사진 1매",false
사증민원,D-8,기업투자,사증발급인정서,대상,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,"기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급인정서 / 대상에 관한 정리입니다. 사증발급인정서 발급대상; 초청사유서; 사업자등록증 사본, 법인등기사항전부증명서; 산업재산권, 그 밖에 이에 준하는 기술과 그 사용에 관한 권리 등을 보유하고 있음을 입증하는 서류",false
사증민원,D-8,기업투자,사증발급인정서,대상,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,"기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급인정서 / 대상에 관한 정리입니다. ※ 한·중 정부간의 사증절차 간소화 및 복수사증 협정 대상자에 해당하지 않으며, 사증(사증발급인정서) 발급 전 국가정보원과 협의 불요; 대리인 신청시 : 위임장, 대리인 재직증명서, 대리인 신분증 추가 제출",false
사증민원,D-8,기업투자,사증발급인정서,제출서류,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,"기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급인정서 / 제출서류에 관한 정리입니다. ※ 출입국·외국인청(사무소·출장소)장은 초청의 진정성, 초청자 및 피초청자의 자격 확인 등을 심사하기 위해 첨부서류의 일부를 가감할 수 있음",false
사증민원,D-8,기업투자,사증발급인정서,요건,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,"기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급인정서 / 요건에 관한 정리입니다. ## 가. 허가요건; 투자대상이 대한민국 국민(개인)이 경영하는 기업일 것; 투자금액이 1억원 이상으로, 투자한 기업의 출자총액의 100분의 10이상을 소유 (외국인투자촉진법시행령 제2조제2항1호)하고 사업자등록증상 한국인과 …",false
사증민원,D-8,기업투자,사증발급,기간,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,"기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급 / 기간에 관한 정리입니다. ## 다. 사증발급; 투자금액, 업종 등을 고려하여 체류기간 1년 이하의 단수사증 발급",false
사증민원,D-8,기업투자,사증발급,수수료,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,"기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급 / 수수료에 관한 정리입니다. 사증발급신청서 (별지 제17호 서식), 여권, 표준규격사진 1매, 수수료; 외국인투자기업등록증 사본; 공동사업자인 국민의 사업자금(사용 내역) 입증서류",false
사증민원,D-8,기업투자,사증발급인정서,대상,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,"기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급인정서 / 대상에 관한 정리입니다. 사증발급인정서발급대상; 공동사업자가 표시된 사업자등록증 사본, 공동사업자약정서 원본; 주재활동의 경우 파견명령서(파견기간 명시) 및 재직증명서; 「외국인투자촉진법 시행규칙」 제16조에 따라 산업통상자원부장관이 지정한 「연구개발…",false
사증민원,D-8,기업투자,사증발급인정서,대상,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,"기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급인정서 / 대상에 관한 정리입니다. 해당국 세관이나 본국 은행 (금융기관)의 외화반출허가(신고)서 (해당자); 투자자금 도입 내역서 (송금확인증, 외국환 매입증명서, 세관신고서 등); ㉯ 현물출자의 경우; 현물출자완료 확인서 사본(관세청장 발행); 세관 수입신고…",false
사증민원,D-8,기업투자,사증발급인정서,제출서류,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,"기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급인정서 / 제출서류에 관한 정리입니다. 자본금 사용내역 입증서류 (물품구매 영수증, 사무실 인테리어 비용, 국내은행 계좌 입출금 내역서 등); 사업장 존재 입증 서류 (사무실 임대차 계약서, 사업장 전경·사무공간·간판 사진 등 자료)",false
사증민원,D-8,기업투자,사증발급인정서,제출서류,2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자,"기업투자(D-8) / 2. 벤처기업 육성에 관한 특별조치법에 따라 벤처기업을 설립한 자 및 예비벤처기업 확인을 받은 자 / 사증발급인정서 / 제출서류에 관한 정리입니다. ※ 재외공관의 장은 입국목적, 초청의 진정성, 초청자 및 피초청자의 자격 확인 등을 심사하기 위해 필요한 경우 첨부서류를 일부 가감할 수 있음",false
사증민원,D-8,기업투자,사증발급,요건,"4. 국내에서 전문학사 이상의 학위를 취득한 사람 또는 외국에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급","기업투자(D-8) / 4. 국내에서 전문학사 이상의 학위를 취득한 사람 또는 외국에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급 / 사증발급 / 요건에 관한 정리입니다. ## 가. 기본요건; 국내에서 전문학사 이상의 학위를 취득한 사람, 또는 외국에서…",false
사증민원,D-8,기업투자,사증발급,일반,"4. 국내에서 전문학사 이상의 학위를 취득한 사람 또는 외국에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급","기업투자(D-8) / 4. 국내에서 전문학사 이상의 학위를 취득한 사람 또는 외국에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급 / 사증발급 / 일반에 관한 정리입니다. 특허권(특허법), 실용신안권(실용신안법), 디자인권(디자인보호법), 상표권(상표법…",true
사증민원,D-8,기업투자,사증발급,제출서류,"4. 국내에서 전문학사 이상의 학위를 취득한 사람 또는 외국에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급","기업투자(D-8) / 4. 국내에서 전문학사 이상의 학위를 취득한 사람 또는 외국에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급 / 사증발급 / 제출서류에 관한 정리입니다. 사증발급인정신청서 (별지 제21호 서식), 여권, 표준규격사진 1매; 법인등기…",false
사증민원,D-8,기업투자,사증발급,제출서류,"4. 국내에서 전문학사 이상의 학위를 취득한 사람 또는 외국에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급","기업투자(D-8) / 4. 국내에서 전문학사 이상의 학위를 취득한 사람 또는 외국에서 학사 이상의 학위를 취득한 사람, 또는 관계 중앙행정기관의 장이 추천한 사람으로서 지식재산권을 보유하거나 이에 준하는 기술력 등을 가진 기술창업자에 대한 기업투자(D-8-4) 사증발급 / 사증발급 / 제출서류에 관한 정리입니다. ※ 출입국 · 외국인청(사무소 · 출장소)장은 초청의 진정성, 초청자 및 피초…",false
사증민원,D-8,기업투자,사증발급,요건,"4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급","기업투자(D-8) / 4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급 / 사증발급 / 요건에 관한 정리입니다. ### 가. 기본요건; 💻 스타트업 코리아 특별비자 추천 민간평가위원회의 심사 승인을 받은 자",false
사증민원,D-8,기업투자,체류자격 변경,제출서류,"4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급","기업투자(D-8) / 4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급 / 체류자격 변경 / 제출서류에 관한 정리입니다. ※ 단, 법인설립이 완료되지 않은 경우에는 법인등기사항전부증명서 및 사업자등록증 사본 제출 생략 가능하며, 입국 후 체류기간(6개월) 이내에 법인등기",false
사증민원,D-8,기업투자,사증발급,제출서류,"4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급","기업투자(D-8) / 4-1. 스타트업 코리아 특별비자 민간평가위원회의 평가를 받고, 중소벤처기업부 장관의 추천을 받은 기술창업자에 대한 기업투자(D-8-4S) 사증발급 / 사증발급 / 제출서류에 관한 정리입니다. 사증발급인정신청서 (별지 제21호 서식), 여권, 표준규격사진 1매; 법인등기사항전부증명서 및 사업자등록증 사본 (제출 가능 시); 스타트업 코리아 특별비자 추천서 (중소벤처기업…",false
사증민원,D-8,기업투자,사증발급,대상,가. 발급대상 : 고용방문자(Employment visitor),"기업투자(D-8) / 가. 발급대상 : 고용방문자(Employment visitor) / 사증발급 / 대상에 관한 정리입니다. ## 가. 발급대상 : 고용방문자(Employment visitor); 정당하게 등록된 회사 또는 기관에 고용되거나 계약에 의하여 기술전문가, 임원, 관리자 등과 같이 숙련된 기술을 요하는 지위에 종사하거나 임용된 자; (예시) 기업내 전근자, 계약서비스 공급자 또…",false
사증민원,D-8,기업투자,사증발급인정서,기간,나. 체류자격 및 체류기간,"기업투자(D-8) / 나. 체류자격 및 체류기간 / 사증발급인정서 / 기간에 관한 정리입니다. ## 나. 체류자격 및 체류기간; 체류자격 : 계약내용 및 파견(고용)형태에 따라 주재(D-7), 기업투자(D-8), 무역경영(D-9), 연구(E-3), 기술지도 (E-4), 특정활동 (E-7) 등의 자격 부여; 사증발급 : 출입국·외국인청(사무소·출장소)의 사증발급인정서에 의해 발급; 고용관련 …",true
사증민원,D-8,기업투자,사증발급인정서,일반,나. 체류자격 및 체류기간,기업투자(D-8) / 나. 체류자격 및 체류기간 / 사증발급인정서 / 일반에 관한 정리입니다. 기업내 전근자; 파견명령서 및 1년 이상의 재직증명서; 지사 또는 연락사무소 설치허가서 사본,true
사증민원,D-8,기업투자,사증발급인정서,제출서류,나. 체류자격 및 체류기간,"기업투자(D-8) / 나. 체류자격 및 체류기간 / 사증발급인정서 / 제출서류에 관한 정리입니다. 계약서비스 공급자 (contractual services suppliers) 또는 이를 지원하는 자; 고용주가 발행한 재직증명서, 인도정부발행; 사업자등록증 등 회사(기관)설립 관련 서류",true
사증민원,D-8,기업투자,사증발급인정서,일반,나. 체류자격 및 체류기간,"기업투자(D-8) / 나. 체류자격 및 체류기간 / 사증발급인정서 / 일반에 관한 정리입니다. 독립전문가 (an independent professionals); 고용 계약서 또는 용역계약서 등 계약을 입증하는 서류; 학위증, 관련 분야 자격증, 1년 이상 해당 분야; 취업경력 입증서류",true
사증민원,D-8,기업투자,사증발급,제한,※ 기업투자(D-8) 사증발급 기본 원칙,"기업투자(D-8) / ※ 기업투자(D-8) 사증발급 기본 원칙 / 사증발급 / 제한에 관한 정리입니다. ## ※ 기업투자(D-8) 사증발급 기본 원칙; 「외국인투자촉진법」에 따른 외국인투자기업의 경영·관리 또는 생산·기술 분야 종사하려는 필수전문인력과 「벤처기업육성에 관한 특별조치법」등에 따라 벤처기업을 설립한 사람중 벤처기업 확인을 받거나 이에 준하는 사람, 법인 창업자 등에 대하여 결격…",false
사증민원,D-8,기업투자,사증발급,예외,※ 기업투자(D-8) 사증발급 기본 원칙,"기업투자(D-8) / ※ 기업투자(D-8) 사증발급 기본 원칙 / 사증발급 / 예외에 관한 정리입니다. ### ≪ 제 한 업 종 ≫; 「사행행위 등 규제 및 처벌 특례법」 제2조제1항제2호 및 동법 시행령 제1조의2에서 규정하고 있는 사행행위 영업(복권발행업, 현상업, 회전판돌리기업, 추첨업, 경품업)을 하려는 자; 식품위생법 시행령 제21조제8호 ‘다’ 목(단란주점) 및 ‘라’ 목(유흥주…",false
사증민원,D-8,기업투자,체류자격 변경,참고,참고사항 관련 판례 : 개인사업자에 대한 기업투자(D-8) 자격관련(대구지법 2010구합4034),기업투자(D-8) / 참고사항 관련 판례 : 개인사업자에 대한 기업투자(D-8) 자격관련(대구지법 2010구합4034) / 체류자격 변경 / 참고에 관한 정리입니다. 참고사항 관련 판례 : 개인사업자에 대한 기업투자(D-8) 자격관련(대구지법 2010구합4034); 처분의 경위; 원고는 스리랑카 국적으로 단기상용(C-2) 자격으로 입국하여 기업투자(D-8) 자격으로 체류자격 변경허가 신청을…,false